"""UI strings of the guided course (fa/en/de). Registered into texts.py via add(S)."""

def add(S, _S):
    S("b_course", "🎓 دورهٔ قدم‌به‌قدم", "🎓 Step-by-step course", "🎓 Schritt-für-Schritt-Kurs")
    S("cr_pick_path", "🧭 <b>از کجا شروع کنیم؟</b>\n\n🎯 <b>تعیین سطح</b>: چند سؤال کوتاه می‌پرسم و بعد پیشنهاد می‌دهم از کجا شروع کنی.\n🌱 <b>از صفر مطلق</b>: دورهٔ قدم‌به‌قدم با من — پینیین و لحن، ریشه‌ها، نوشتن، HSK ۱ تا ۳؛ هر درس: توضیح کوتاه ← تمرین با اصلاح ← درس بعدی.\n🤷 <b>خودم انتخاب می‌کنم / نمی‌دانم</b>: سطح را خودت می‌گویی (و می‌توانی هر وقت دورهٔ صفر را هم شروع کنی).",
      "🧭 <b>Where shall we start?</b>\n\n🎯 <b>Placement test</b>: a few short questions, then I recommend where to start.\n🌱 <b>Absolute zero</b>: the guided step-by-step course with me — pinyin & tones, radicals, writing, HSK 1–3; each lesson: short explanation → practice with corrections → next lesson.\n🤷 <b>I'll choose / I don't know</b>: pick your own level (you can still start the zero course any time).",
      "🧭 <b>Wo fangen wir an?</b>\n\n🎯 <b>Einstufungstest</b>: ein paar kurze Fragen, dann empfehle ich dir den Einstieg.\n🌱 <b>Ganz von null</b>: der geführte Schritt-für-Schritt-Kurs mit mir — Pinyin & Töne, Radikale, Schreiben, HSK 1–3; jede Lektion: kurze Erklärung → Übung mit Korrektur → nächste Lektion.\n🤷 <b>Ich wähle selbst / weiß nicht</b>: Niveau selbst wählen (den Nullkurs kannst du jederzeit starten).")
    S("cr_b_place", "🎯 تعیین سطح", "🎯 Placement test", "🎯 Einstufungstest")
    S("cr_b_zero", "🌱 از صفر مطلق، قدم‌به‌قدم با ربات", "🌱 From absolute zero, step by step", "🌱 Ganz von null, Schritt für Schritt")
    S("cr_b_zero2", "🌱 دورهٔ قدم‌به‌قدم از صفر", "🌱 Guided course from zero", "🌱 Geführter Kurs von null")
    S("cr_b_self", "🤷 خودم انتخاب می‌کنم / نمی‌دانم", "🤷 I'll choose / I don't know", "🤷 Ich wähle selbst / weiß nicht")
    S("cr_self_text", "📶 سطح فعلی‌ات را انتخاب کن — یا اگر مطمئن نیستی، بهتر است دورهٔ قدم‌به‌قدم را از صفر شروع کنیم 👇", "📶 Pick your current level — or, if you're not sure, it's best to start the guided course from zero 👇", "📶 Wähle dein Niveau — oder, wenn du unsicher bist, starten wir am besten den geführten Kurs von null 👇")
    S("cr_ob_ready", "✅ عالی! حالا فقط یک سؤال کوتاه:", "✅ Great! One quick question first:", "✅ Super! Erst noch eine kurze Frage:")
    S("cr_hub", "🎓 <b>دورهٔ قدم‌به‌قدم</b> — {pct}٪ پیش رفته‌ای\n\n{head}\n\n{mods}", "🎓 <b>Step-by-step course</b> — {pct}% done\n\n{head}\n\n{mods}", "🎓 <b>Schritt-für-Schritt-Kurs</b> — {pct} % geschafft\n\n{head}\n\n{mods}")
    S("cr_hub_cur", "📍 درس {i} از {n}: <b>{title}</b>\nوضعیت: {st}", "📍 Lesson {i} of {n}: <b>{title}</b>\nStatus: {st}", "📍 Lektion {i} von {n}: <b>{title}</b>\nStatus: {st}")
    S("cr_hub_done", "🏆 همهٔ درس‌ها را گذراندی! از «شروع دوباره» یا «فهرست درس‌ها» برای مرور استفاده کن.", "🏆 You've finished every lesson! Use “Restart” or the lesson list to review.", "🏆 Du hast alle Lektionen geschafft! Nutze „Neu starten“ oder die Lektionsliste zur Wiederholung.")
    S("cr_st_teach", "آموزش", "teaching", "Erklärung")
    S("cr_st_practice", "تمرین", "practice", "Übung")
    S("cr_st_retry", "نیاز به تکرار", "needs another try", "noch einmal versuchen")
    S("cr_b_go", "▶️ ادامه درس", "▶️ Continue lesson", "▶️ Lektion fortsetzen")
    S("cr_b_jump", "🗺 فهرست درس‌ها / پرش", "🗺 Lessons / jump", "🗺 Lektionen / springen")
    S("cr_b_skip", "⏭ رد کردن این درس", "⏭ Skip this lesson", "⏭ Lektion überspringen")
    S("cr_b_restart", "🔄 شروع دوباره", "🔄 Restart", "🔄 Neu starten")
    S("cr_b_hub", "🎓 دوره", "🎓 Course", "🎓 Kurs")
    S("cr_b_practice", "✍️ شروع تمرین", "✍️ Start practice", "✍️ Übung starten")
    S("cr_b_again", "🔁 دوباره تمرین", "🔁 Practise again", "🔁 Nochmal üben")
    S("cr_b_review_lesson", "📖 مرور توضیح درس", "📖 Re-read the lesson", "📖 Lektion nochmal lesen")
    S("cr_b_next_lesson", "➡️ درس بعدی", "➡️ Next lesson", "➡️ Nächste Lektion")
    S("cr_b_take_rec", "✅ شروع از جای پیشنهادی", "✅ Start at the recommended place", "✅ Beim Vorschlag beginnen")
    S("cr_b_yes_restart", "⚠️ بله، از اول شروع کن", "⚠️ Yes, restart from the beginning", "⚠️ Ja, ganz von vorn")
    S("cr_zero_intro", "🌱 <b>شروع از صفر مطلق</b>\nدورهٔ ما {n} درس دارد با ترتیب ثابت: پینیین و لحن‌ها ← ۵۱ ریشه ← اصول نوشتن ← اولین نویسه‌ها ← HSK ۱ (لغت، دستور، جمله) ← HSK ۲ ← HSK ۳.\nهر درس: توضیح کوتاه ← تمرین با اصلاح ← با حداقل ۷۰٪ درست، درس بعدی باز می‌شود.\nهر وقت خواستی برگرد: «▶️ ادامه درس» دقیقاً از همان‌جا ادامه می‌دهد.",
      "🌱 <b>Starting from absolute zero</b>\nThe course has {n} lessons in a fixed order: pinyin & tones → 51 radicals → writing basics → first characters → HSK 1 (words, grammar, sentences) → HSK 2 → HSK 3.\nEach lesson: short explanation → practice with corrections → with ≥ 70 % correct the next lesson unlocks.\nCome back any time: “▶️ Continue lesson” resumes exactly where you stopped.",
      "🌱 <b>Start bei null</b>\nDer Kurs hat {n} Lektionen in fester Reihenfolge: Pinyin & Töne → 51 Radikale → Schreibgrundlagen → erste Zeichen → HSK 1 (Wörter, Grammatik, Sätze) → HSK 2 → HSK 3.\nJede Lektion: kurze Erklärung → Übung mit Korrektur → ab 70 % richtig wird die nächste frei.\nKomm jederzeit zurück: „▶️ Lektion fortsetzen“ macht genau dort weiter.")
    S("cr_lesson_head", "🎓 <b>درس {i} از {n}</b> · {mod}\n📌 <b>{title}</b>", "🎓 <b>Lesson {i} of {n}</b> · {mod}\n📌 <b>{title}</b>", "🎓 <b>Lektion {i} von {n}</b> · {mod}\n📌 <b>{title}</b>")
    S("cr_method", "🧭 روش یادگیری: {m}", "🧭 Method: {m}", "🧭 Methode: {m}")
    S("cr_tips_head", "💡 <b>نکته‌های تمایز و یادگیری</b>", "💡 <b>Tips to tell sounds apart</b>", "💡 <b>Tipps zur Unterscheidung</b>")
    S("cr_examples", "مثال", "examples", "Beispiele")
    S("cr_srs_note", "🔁 این واژه‌ها به جعبهٔ مرور (لایتنر / SM-2) اضافه شدند؛ پاسخ‌های تمرین زمان مرور بعدی را تعیین می‌کند.", "🔁 These words were added to your review box (Leitner / SM-2); your practice answers set when you see them next.", "🔁 Diese Wörter liegen jetzt in deiner Wiederholungsbox (Leitner / SM-2); deine Antworten bestimmen die nächste Wiederholung.")
    S("cr_in_sentences", "🧩 <b>همین واژه‌ها در جمله</b>", "🧩 <b>The same words in sentences</b>", "🧩 <b>Dieselben Wörter in Sätzen</b>")
    S("cr_sent_none", "این بار جملهٔ نمونه‌ای پیدا نشد؛ مستقیم برو سراغ تمرین.", "No example sentences this time; go straight to the practice.", "Diesmal keine Beispielsätze; gehe direkt zur Übung.")
    S("cr_marks_body", "📏 <b>علامت لحن روی کدام حرف می‌رود؟</b>\n{rules}\n\nمثال‌ها: <b>{ex}</b>", "📏 <b>Which letter gets the tone mark?</b>\n{rules}\n\nExamples: <b>{ex}</b>", "📏 <b>Auf welchen Buchstaben kommt das Tonzeichen?</b>\n{rules}\n\nBeispiele: <b>{ex}</b>")
    S("cr_pycheck_body", "🔤 <b>مرور پینیین</b>\nحالا فقط گوش بده: حرف آغازین، وان و لحن را از روی صدا تشخیص بده. اگر جایی گیر کردی، از دکمه‌های زیر یادداشت‌هایت را ببین.", "🔤 <b>Pinyin checkpoint</b>\nJust listen: recognise initials, finals and tones by ear. If you get stuck, peek at your notes with the buttons below.", "🔤 <b>Pinyin-Wiederholung</b>\nNur hören: Anlaute, Finale und Töne am Klang erkennen. Wenn du hängst, schau mit den Tasten unten in deine Notizen.")
    S("cr_rad_p2", "🧠 <b>هر ریشه در یک نویسه</b>\nبه شکل ریشه نگاه کن و در نویسه پیدایش کن:", "🧠 <b>Each radical inside a character</b>\nLook at the radical's shape and spot it in the character:", "🧠 <b>Jedes Radikal in einem Zeichen</b>\nSieh dir die Form an und finde es im Zeichen:")
    S("cr_order_body", "✍️ <b>قاعده‌های ترتیب نوشتن</b>\n{rules}\n\nروی دکمه‌ها بزن تا ترتیب ضربه‌ها را ببینی.", "✍️ <b>Stroke-order rules</b>\n{rules}\n\nTap a button to see the stroke order.", "✍️ <b>Regeln der Strichfolge</b>\n{rules}\n\nTippe auf eine Taste, um die Strichfolge zu sehen.")
    S("cr_check_body", "🔁 <b>مرور مخلوط</b>\nچند سؤال متنوع از واژه‌های همین بخش. آرام و دقیق جواب بده.", "🔁 <b>Mixed review</b>\nA few varied questions on the words of this section. Take your time.", "🔁 <b>Gemischte Wiederholung</b>\nEinige abwechslungsreiche Fragen zu den Wörtern dieses Abschnitts.")
    S("cr_practice_intro", "✍️ <b>تمرین درس: {title}</b>\n{n} سؤال — برای قبولی حداقل {need} پاسخ درست لازم است. اشتباه‌ها را همان لحظه توضیح می‌دهم.", "✍️ <b>Practice: {title}</b>\n{n} questions — you need at least {need} correct to pass. I'll explain mistakes right away.", "✍️ <b>Übung: {title}</b>\n{n} Fragen — zum Bestehen brauchst du mindestens {need} richtige. Fehler erkläre ich sofort.")
    S("cr_paused", "⏸ تمرین «{title}» نگه داشته شد ({pos}/{n} پاسخ داده‌ای). هر وقت خواستی «▶️ ادامه درس» را بزن؛ از همین سؤال ادامه می‌دهیم.", "⏸ Practice “{title}” is on hold ({pos}/{n} answered). Press “▶️ Continue lesson” any time; we resume at this question.", "⏸ Die Übung „{title}“ ist pausiert ({pos}/{n} beantwortet). Drücke jederzeit „▶️ Lektion fortsetzen“; wir machen bei dieser Frage weiter.")
    S("cr_pass", "🎉 <b>درس قبول شد!</b>\n✅ {ok} از {n} → <b>{pct}٪</b> (+۲۰ امتیاز)\n{nxt}", "🎉 <b>Lesson passed!</b>\n✅ {ok} of {n} → <b>{pct}%</b> (+20 XP)\n{nxt}", "🎉 <b>Lektion bestanden!</b>\n✅ {ok} von {n} → <b>{pct} %</b> (+20 XP)\n{nxt}")
    S("cr_next_is", "➡️ درس بعدی: <b>{title}</b>", "➡️ Next lesson: <b>{title}</b>", "➡️ Nächste Lektion: <b>{title}</b>")
    S("cr_all_done", "🏆 این آخرین درس بود — دوره تمام شد! مرور روزانه را فراموش نکن.", "🏆 That was the last lesson — course complete! Keep up your daily review.", "🏆 Das war die letzte Lektion — Kurs abgeschlossen! Wiederhole täglich weiter.")
    S("cr_fail", "😕 <b>هنوز کامل نیست</b>\n✅ {ok} از {n} → {pct}٪ (حداقل {need} درست لازم است).\nبی‌خیال؛ توضیح را دوباره بخوان یا همین تمرین را با سؤال‌های تازه تکرار کن. اشتباه‌ها در «مرور اشتباه‌ها» ذخیره شدند.", "😕 <b>Not quite yet</b>\n✅ {ok} of {n} → {pct}% (you need {need}).\nNo worries; re-read the explanation or repeat the practice with fresh questions. Your mistakes are saved under “Mistakes”.", "😕 <b>Noch nicht ganz</b>\n✅ {ok} von {n} → {pct} % (nötig: {need}).\nKein Problem; lies die Erklärung nochmal oder wiederhole die Übung mit neuen Fragen. Deine Fehler sind unter „Fehler“ gespeichert.")
    S("cr_retry", "🔁 درس «{title}» هنوز قبول نشده. چه کار کنیم؟", "🔁 The lesson “{title}” isn't passed yet. What now?", "🔁 Die Lektion „{title}“ ist noch nicht bestanden. Was jetzt?")
    S("cr_place_intro", "🎯 <b>تعیین سطح</b>\n{n} سؤال کوتاه: ۳ سؤال از آواها و لحن، ۳ تا از هر سطح HSK ۱ تا ۳. حدس زدن اشکال ندارد؛ فقط برای پیدا کردن نقطهٔ شروع است.", "🎯 <b>Placement test</b>\n{n} short questions: 3 on sounds & tones, 3 from each HSK level 1–3. Guessing is fine; it only finds your starting point.", "🎯 <b>Einstufungstest</b>\n{n} kurze Fragen: 3 zu Lauten & Tönen, je 3 aus HSK 1–3. Raten ist okay; es geht nur um deinen Startpunkt.")
    S("cr_place_stopped", "⏹ تعیین سطح نیمه‌کاره ماند. هر وقت خواستی دوباره شروع کن.", "⏹ The placement test was left unfinished. Start it again whenever you like.", "⏹ Der Einstufungstest wurde nicht beendet. Starte ihn jederzeit neu.")
    S("cr_tier0", "آواها و لحن", "Sounds & tones", "Laute & Töne")
    S("cr_place_result", "🎯 <b>نتیجهٔ تعیین سطح</b>\n{lines}\n\n{rec}\n📍 پیشنهاد شروع: <b>{start}</b> ({mod})", "🎯 <b>Placement result</b>\n{lines}\n\n{rec}\n📍 Suggested start: <b>{start}</b> ({mod})", "🎯 <b>Einstufungsergebnis</b>\n{lines}\n\n{rec}\n📍 Empfohlener Start: <b>{start}</b> ({mod})")
    S("cr_rec_zero", "🌱 آوا و لحن هنوز محکم نیست؛ بهتر است از صفر و با پینیین شروع کنی.", "🌱 Sounds and tones aren't solid yet; best to start from zero with pinyin.", "🌱 Laute und Töne sind noch nicht sicher; am besten bei null mit Pinyin starten.")
    S("cr_rec_rad", "🧱 آوا را بلدی ولی واژه‌ها هنوز کم است؛ از ریشه‌ها و نوشتن شروع کن.", "🧱 You know the sounds but few words yet; start with radicals and writing.", "🧱 Du kennst die Laute, aber noch wenige Wörter; starte mit Radikalen und Schreiben.")
    S("cr_rec_h1", "1️⃣ پایهٔ خوبی داری؛ از واژه‌ها و دستور HSK ۱ شروع کن.", "1️⃣ You have a good base; start with HSK 1 words and grammar.", "1️⃣ Du hast eine gute Basis; starte mit HSK-1-Wörtern und -Grammatik.")
    S("cr_rec_h2", "2️⃣ HSK ۱ را خوب می‌دانی؛ از HSK ۲ شروع کن.", "2️⃣ You know HSK 1 well; start with HSK 2.", "2️⃣ HSK 1 sitzt gut; starte mit HSK 2.")
    S("cr_rec_h3", "3️⃣ عالی! از HSK ۳ شروع کن (هر درس قبلی را می‌توانی از فهرست بازدید کنی).", "3️⃣ Excellent! Start with HSK 3 (you can revisit earlier lessons from the list).", "3️⃣ Ausgezeichnet! Starte mit HSK 3 (frühere Lektionen findest du in der Liste).")
    S("cr_jump_title", "🗺 <b>فهرست درس‌ها</b>\nبخش را انتخاب کن؛ می‌توانی به هر درسی بپری.", "🗺 <b>Lessons</b>\nPick a section; you can jump to any lesson.", "🗺 <b>Lektionen</b>\nWähle einen Abschnitt; du kannst zu jeder Lektion springen.")
    S("cr_jump_mod", "🗺 <b>{mod}</b>\n▶️ درس فعلی • ✅ قبول • ⏭ ردشده", "🗺 <b>{mod}</b>\n▶️ current • ✅ passed • ⏭ skipped", "🗺 <b>{mod}</b>\n▶️ aktuell • ✅ bestanden • ⏭ übersprungen")
    S("cr_restart_q", "⚠️ دوره از درس اول شروع می‌شود و پیشرفت درس‌ها پاک می‌شود (کارت‌های مرورت می‌مانند). مطمئنی؟", "⚠️ The course restarts at lesson 1 and lesson progress is cleared (your review cards stay). Sure?", "⚠️ Der Kurs beginnt wieder bei Lektion 1, der Lektionsfortschritt wird gelöscht (deine Wiederholungskarten bleiben). Sicher?")
    S("cr_remind_line", "🎓 درس بعدی دورهٔ تو: <b>{title}</b>", "🎓 Your next course lesson: <b>{title}</b>", "🎓 Deine nächste Kurslektion: <b>{title}</b>")
    S("cr_progress_line", "🎓 <b>دورهٔ قدم‌به‌قدم:</b> {pct}٪ ({d}/{n} درس)", "🎓 <b>Step-by-step course:</b> {pct}% ({d}/{n} lessons)", "🎓 <b>Kurs:</b> {pct} % ({d}/{n} Lektionen)")
    # help text: mention /course
    for i, line in enumerate(("🎓 /course — دورهٔ قدم‌به‌قدم از صفر + 🎯 /placement تعیین سطح\n", "🎓 /course — guided course from zero + 🎯 /placement test\n", "🎓 /course — geführter Kurs von null + 🎯 /placement Einstufungstest\n")):
        k = "💡"
        h = list(_S["help"]); h[i] = h[i].replace(k, line + "\n" + k, 1) if k in h[i] else h[i] + "\n" + line
        _S["help"] = tuple(h)
