"""UI strings in Persian / English / German. Every key has all three languages (checked by tests)."""
_S = {}
def S(key, fa, en, de): _S[key] = (fa, en, de)

# ---------- general ----------
S("welcome", "👋 سلام! من <b>{name}</b> هستم، معلم خصوصی چینی (ماندارین) برای فارسی‌زبان‌ها.\n\n🎯 با من از صفر شروع می‌کنی: آوا و لحن، حروف و ریشه‌ها، لغات HSK ۱ تا ۳، تمرین و مرور هوشمند.\n👇 فقط یکی از دکمه‌ها را بزن. هر وقت خواستی یک واژه یا سؤال بفرست.",
  "👋 Hi! I'm <b>{name}</b>, your private Mandarin Chinese teacher.\n\n🎯 Start from zero: sounds & tones, characters & radicals, HSK 1–3 vocabulary, exercises and smart review.\n👇 Just tap a button. Send me any word or question any time.",
  "👋 Hallo! Ich bin <b>{name}</b>, dein privater Mandarin-Lehrer.\n\n🎯 Starte bei null: Laute & Töne, Zeichen & Radikale, HSK-1–3-Vokabeln, Übungen und smarte Wiederholung.\n👇 Tippe einfach auf einen Knopf. Schick mir jederzeit ein Wort oder eine Frage.")
S("pick_ui", "🌐 زبان ربات را انتخاب کن:", "🌐 Choose the bot language:", "🌐 Wähle die Sprache des Bots:")
S("pick_expl", "💬 توضیحات و معنی‌ها به کدام زبان باشد؟", "💬 In which language should explanations and meanings be?", "💬 In welcher Sprache sollen Erklärungen und Bedeutungen sein?")
S("pick_level", "📶 سطح فعلی‌ات چیست؟", "📶 What is your current level?", "📶 Was ist dein aktuelles Niveau?")
S("lvl_0", "🌱 مبتدی (صفر)", "🌱 Absolute beginner", "🌱 Absoluter Anfänger")
S("lvl_1", "HSK 1", "HSK 1", "HSK 1")
S("lvl_2", "HSK 2", "HSK 2", "HSK 2")
S("lvl_3", "HSK 3", "HSK 3", "HSK 3")
S("onboard_done", "✅ آماده‌ایم! سطح: <b>{level}</b> — توضیحات: <b>{expl}</b>.\nپیشنهاد من: اول «📅 درس امروز» را بزن.", "✅ All set! Level: <b>{level}</b> — explanations: <b>{expl}</b>.\nMy suggestion: start with “📅 Today's lesson”.", "✅ Alles bereit! Niveau: <b>{level}</b> — Erklärungen: <b>{expl}</b>.\nMein Vorschlag: Starte mit „📅 Heutige Lektion“.")
S("menu_title", "🏠 <b>منوی اصلی</b>\nچه کار کنیم؟", "🏠 <b>Main menu</b>\nWhat shall we do?", "🏠 <b>Hauptmenü</b>\nWas machen wir?")
S("b_today", "📅 درس امروز", "📅 Today's lesson", "📅 Heutige Lektion")
S("b_learn", "📖 یادگیری لغت", "📖 Learn words", "📖 Vokabeln lernen")
S("b_quiz", "🧠 تمرین", "🧠 Practice", "🧠 Üben")
S("b_review", "🔁 مرور", "🔁 Review", "🔁 Wiederholen")
S("b_dict", "🔍 دیکشنری", "🔍 Dictionary", "🔍 Wörterbuch")
S("b_ask", "💬 بپرس", "💬 Ask", "💬 Fragen")
S("b_alpha", "🔤 آوا و حروف", "🔤 Sounds & characters", "🔤 Laute & Zeichen")
S("b_read", "📚 داستان کوتاه", "📚 Short stories", "📚 Kurztexte")
S("b_progress", "📊 پیشرفت", "📊 Progress", "📊 Fortschritt")
S("b_settings", "⚙️ تنظیمات", "⚙️ Settings", "⚙️ Einstellungen")
S("b_help", "ℹ️ راهنما", "ℹ️ Help", "ℹ️ Hilfe")
S("b_menu", "🏠 منو", "🏠 Menu", "🏠 Menü")
S("b_back", "⬅️ برگشت", "⬅️ Back", "⬅️ Zurück")
S("b_next", "➡️ بعدی", "➡️ Next", "➡️ Weiter")
S("b_skip", "⏭ رد شدن", "⏭ Skip", "⏭ Überspringen")
S("b_stop", "⏹ پایان", "⏹ Stop", "⏹ Beenden")
S("b_hear", "🔊 بشنو", "🔊 Listen", "🔊 Anhören")
S("b_strokes", "✍️ ترتیب خط‌ها", "✍️ Stroke order", "✍️ Strichfolge")
S("b_parts", "🧩 اجزا", "🧩 Components", "🧩 Bestandteile")
S("b_story", "💡 یادیار", "💡 Memory hint", "💡 Eselsbrücke")
S("b_more_ex", "📝 مثال بیشتر", "📝 More examples", "📝 Mehr Beispiele")
S("b_know", "✅ بلد بودم", "✅ I knew it", "✅ Wusste ich")
S("b_dontknow", "❌ بلد نبودم", "❌ I didn't know", "❌ Wusste ich nicht")
S("b_show", "👁 نمایش جواب", "👁 Show answer", "👁 Antwort zeigen")
S("b_again", "🔄 دوباره", "🔄 Again", "🔄 Nochmal")
S("b_cont_pm", "💬 ادامه در خصوصی", "💬 Continue in private", "💬 Privat weitermachen")
S("b_open_pm", "💬 باز کردن چت خصوصی", "💬 Open private chat", "💬 Privatchat öffnen")
S("b_practice_bot", "📝 تمرین در ربات", "📝 Practice in the bot", "📝 Im Bot üben")
S("b_yes", "✅ بله", "✅ Yes", "✅ Ja")
S("b_no", "❌ خیر", "❌ No", "❌ Nein")
S("cancelled", "لغو شد.", "Cancelled.", "Abgebrochen.")
S("unexpected", "⚠️ مشکلی پیش آمد؛ دوباره تلاش کن.", "⚠️ Something went wrong; please try again.", "⚠️ Etwas ist schiefgelaufen; bitte versuche es erneut.")
S("banned", "⛔ دسترسی شما به این ربات بسته شده است.", "⛔ Your access to this bot has been blocked.", "⛔ Dein Zugang zu diesem Bot wurde gesperrt.")
S("rate_limited", "⏳ کمی آهسته‌تر لطفاً.", "⏳ Please slow down a little.", "⏳ Bitte etwas langsamer.")
S("unknown_cmd", "این دستور را نمی‌شناسم. از منو استفاده کن 👇", "I don't know that command. Use the menu 👇", "Diesen Befehl kenne ich nicht. Nutze das Menü 👇")
S("help", "ℹ️ <b>راهنما</b>\n\n📅 /today — درس امروز (لغت جدید + مرور + تمرین)\n📖 /learn — یادگیری لغت‌های تازه\n🧠 /quiz — تمرین با انواع سؤال (اصلاح و توضیح خطاها)\n🔁 /review — مرور با جعبه لایتنر\n🔍 /dict <i>واژه</i> — دیکشنری (چینی، پینیین، فارسی، انگلیسی، آلمانی)\n💬 /ask <i>سؤال</i> — پرسش دستور زبان و کاربرد\n🔤 /alphabet — پینیین، لحن‌ها، ریشه‌ها، ترتیب خط\n📚 /read — داستان‌های کوتاه با پینیین\n📊 /progress — پیشرفت و آمار\n⚙️ /settings — زبان، سطح، روش‌ها، یادآور\n\n💡 هر واژه‌ای (چینی، پینیین، فارسی، انگلیسی یا آلمانی) بفرستی، خودم معنی می‌کنم.\n\n👥 <b>در گروه</b>: /quiz /word /dict /ask — یا ربات را منشن کن یا روی پیامش ریپلای بزن.",
  "ℹ️ <b>Help</b>\n\n📅 /today — today's lesson (new words + review + practice)\n📖 /learn — learn new words\n🧠 /quiz — exercises of many types (with corrections and explanations)\n🔁 /review — Leitner-box review\n🔍 /dict <i>word</i> — dictionary (Chinese, pinyin, Persian, English, German)\n💬 /ask <i>question</i> — grammar & usage questions\n🔤 /alphabet — pinyin, tones, radicals, stroke order\n📚 /read — short stories with pinyin\n📊 /progress — progress & stats\n⚙️ /settings — language, level, methods, reminder\n\n💡 Send any word (Chinese, pinyin, Persian, English or German) and I'll translate it.\n\n👥 <b>In groups</b>: /quiz /word /dict /ask — or mention the bot / reply to its message.",
  "ℹ️ <b>Hilfe</b>\n\n📅 /today — heutige Lektion (neue Wörter + Wiederholung + Übung)\n📖 /learn — neue Vokabeln lernen\n🧠 /quiz — Übungen verschiedener Art (mit Korrektur und Erklärung)\n🔁 /review — Wiederholung mit Leitner-Boxen\n🔍 /dict <i>Wort</i> — Wörterbuch (Chinesisch, Pinyin, Persisch, Englisch, Deutsch)\n💬 /ask <i>Frage</i> — Grammatik- und Gebrauchsfragen\n🔤 /alphabet — Pinyin, Töne, Radikale, Strichfolge\n📚 /read — Kurztexte mit Pinyin\n📊 /progress — Fortschritt & Statistik\n⚙️ /settings — Sprache, Niveau, Methoden, Erinnerung\n\n💡 Schick mir ein beliebiges Wort (Chinesisch, Pinyin, Persisch, Englisch oder Deutsch) und ich übersetze es.\n\n👥 <b>In Gruppen</b>: /quiz /word /dict /ask — oder den Bot erwähnen / auf seine Nachricht antworten.")

# ---------- words / cards ----------
S("card", "{hz}\n<b>{py}</b>\n{lvl}\n\n{mean}{src}{ex}", "{hz}\n<b>{py}</b>\n{lvl}\n\n{mean}{src}{ex}", "{hz}\n<b>{py}</b>\n{lvl}\n\n{mean}{src}{ex}")
S("src_hande", "\n<i>منبع آلمانی: HanDeDict</i>", "\n<i>German source: HanDeDict</i>", "\n<i>Quelle: HanDeDict</i>")
S("src_llm", "\n<i>ترجمهٔ خودکار (هوش مصنوعی)</i>", "\n<i>machine-translated (AI)</i>", "\n<i>maschinell übersetzt (KI)</i>")
S("src_missing", "\n<i>⚠️ ترجمه به این زبان موجود نیست؛ معنی انگلیسی نمایش داده شد.</i>", "\n<i>⚠️ no translation in this language; English shown.</i>", "\n<i>⚠️ keine Übersetzung in dieser Sprache; Englisch angezeigt.</i>")
S("example_line", "\n\n📝 <b>مثال:</b> {zh}\n<i>{py}</i>\n{tr}", "\n\n📝 <b>Example:</b> {zh}\n<i>{py}</i>\n{tr}", "\n\n📝 <b>Beispiel:</b> {zh}\n<i>{py}</i>\n{tr}")
S("learn_intro", "📖 <b>لغت جدید</b> ({i}/{n})", "📖 <b>New word</b> ({i}/{n})", "📖 <b>Neues Wort</b> ({i}/{n})")
S("learn_done", "🎉 همهٔ لغت‌های جدید امروز را دیدی! حالا کمی تمرین کنیم؟", "🎉 You've seen all new words for today! Practise a bit now?", "🎉 Du hast alle neuen Wörter für heute gesehen! Jetzt ein bisschen üben?")
S("learn_none", "🏆 لغت جدیدی در این سطح نمانده! سطحت را از تنظیمات بالا ببر یا مرور کن.", "🏆 No new words left at this level! Raise your level in settings or review.", "🏆 Keine neuen Wörter mehr auf diesem Niveau! Erhöhe dein Niveau in den Einstellungen oder wiederhole.")
S("lvl_tag", "📶 HSK {lv}", "📶 HSK {lv}", "📶 HSK {lv}")
S("strokes_cap", "✍️ ترتیب نوشتن <b>{ch}</b> — {n} خط. قرمز = خطِ تازه.\n<i>داده: Make Me a Hanzi (Arphic PL)</i>", "✍️ Stroke order of <b>{ch}</b> — {n} strokes. Red = newest stroke.\n<i>Data: Make Me a Hanzi (Arphic PL)</i>", "✍️ Strichfolge von <b>{ch}</b> — {n} Striche. Rot = neuester Strich.\n<i>Daten: Make Me a Hanzi (Arphic PL)</i>")
S("strokes_none", "برای این نویسه داده‌ی ترتیب خط ندارم.", "I have no stroke data for this character.", "Für dieses Zeichen habe ich keine Strichdaten.")
S("parts", "🧩 <b>اجزای {ch}</b>\nریشه: <b>{rad}</b>\n{parts}{ety}", "🧩 <b>Components of {ch}</b>\nRadical: <b>{rad}</b>\n{parts}{ety}", "🧩 <b>Bestandteile von {ch}</b>\nRadikal: <b>{rad}</b>\n{parts}{ety}")
S("parts_none", "برای این نویسه اطلاعات اجزا ندارم.", "No component data for this character.", "Keine Bestandteil-Daten für dieses Zeichen.")
S("ety_line", "\n💡 {hint}", "\n💡 {hint}", "\n💡 {hint}")
S("story_head", "💡 <b>یادیار برای {hz}</b>", "💡 <b>Memory hint for {hz}</b>", "💡 <b>Eselsbrücke für {hz}</b>")
S("story_auto", "با اجزای این نویسه داستانی بساز و در ذهنت تصویرش کن. هر چه خنده‌دارتر، ماندگارتر!", "Make up a story from the character's parts and picture it. The funnier, the more memorable!", "Erfinde eine Geschichte aus den Teilen des Zeichens und stell sie dir vor. Je lustiger, desto einprägsamer!")
S("story_sound", "🔊 صدا: <b>{py}</b> — برای یادآوری آوا، یک واژهٔ آشنا که شبیه این صداست پیدا کن.", "🔊 Sound: <b>{py}</b> — find a familiar word that sounds similar to anchor the pronunciation.", "🔊 Klang: <b>{py}</b> — such dir ein ähnlich klingendes Wort als Anker für die Aussprache.")

# ---------- dictionary / ask ----------
S("dict_prompt", "🔍 یک واژه بفرست: چینی (学校)، پینیین (xuexiao / xué xiào)، فارسی (مدرسه)، انگلیسی (school) یا آلمانی (Schule).", "🔍 Send a word: Chinese (学校), pinyin (xuexiao / xué xiào), Persian (مدرسه), English (school) or German (Schule).", "🔍 Schick ein Wort: Chinesisch (学校), Pinyin (xuexiao / xué xiào), Persisch (مدرسه), Englisch (school) oder Deutsch (Schule).")
S("dict_none", "😕 چیزی برای «{q}» پیدا نکردم. املا را بررسی کن یا انگلیسی/پینیین بفرست.\n<i>نکته: جستجوی فارسی فقط روی لغات HSK ۱–۳ است.</i>", "😕 Nothing found for “{q}”. Check the spelling or try English/pinyin.\n<i>Note: Persian search only covers the HSK 1–3 words.</i>", "😕 Nichts gefunden für „{q}“. Prüfe die Schreibweise oder versuche Englisch/Pinyin.\n<i>Hinweis: Die persische Suche deckt nur HSK-1–3-Wörter ab.</i>")
S("dict_entry", "<b>{hz}</b>  {trad}\n<b>{py}</b> {lvl}\n{mean}{src}", "<b>{hz}</b>  {trad}\n<b>{py}</b> {lvl}\n{mean}{src}", "<b>{hz}</b>  {trad}\n<b>{py}</b> {lvl}\n{mean}{src}")
S("dict_chars", "\n🔠 <b>نویسه‌ها:</b>\n{chars}", "\n🔠 <b>Characters:</b>\n{chars}", "\n🔠 <b>Zeichen:</b>\n{chars}")
S("dict_more", "… و {n} نتیجهٔ دیگر", "… and {n} more", "… und {n} weitere")
S("dict_credit", "\n<i>منابع: CC-CEDICT (CC BY-SA)، HanDeDict، Make Me a Hanzi</i>", "\n<i>Sources: CC-CEDICT (CC BY-SA), HanDeDict, Make Me a Hanzi</i>", "\n<i>Quellen: CC-CEDICT (CC BY-SA), HanDeDict, Make Me a Hanzi</i>")
S("dict_nodata", "⚠️ فایل دیکشنری روی سرور ساخته نشده (build_data.py).", "⚠️ The dictionary file has not been built on the server (build_data.py).", "⚠️ Die Wörterbuchdatei wurde auf dem Server nicht erzeugt (build_data.py).")
S("seg_head", "🧱 <b>تجزیهٔ جمله:</b>", "🧱 <b>Sentence breakdown:</b>", "🧱 <b>Satzzerlegung:</b>")
S("ask_prompt", "💬 سؤالت را بنویس (دستور زبان، کاربرد واژه، تفاوت دو واژه، ترجمهٔ جمله...).", "💬 Write your question (grammar, word usage, difference between words, sentence translation…).", "💬 Schreib deine Frage (Grammatik, Wortgebrauch, Unterschied zweier Wörter, Satzübersetzung …).")
S("ask_thinking", "⌛ دارم فکر می‌کنم…", "⌛ Thinking…", "⌛ Ich denke nach …")
S("ask_nollm", "ℹ️ هوش مصنوعی فعال نیست، پس این‌ها را از یادداشت‌های دستور زبان و دیکشنری آفلاین برایت پیدا کردم.\n<i>(مدیر می‌تواند با کلید API پاسخ‌های کامل را فعال کند.)</i>", "ℹ️ AI answers are not enabled, so here is what I found in my offline grammar notes and dictionary.\n<i>(The admin can enable full answers with an API key.)</i>", "ℹ️ KI-Antworten sind nicht aktiviert, daher findest du hier meine Offline-Grammatiknotizen und das Wörterbuch.\n<i>(Der Admin kann mit einem API-Schlüssel volle Antworten aktivieren.)</i>")
S("ask_nothing", "نتوانستم پاسخ مشخصی پیدا کنم. این‌ها را امتحان کن: یک واژه برای /dict بفرست، یا مبحثی مثل «了»، «的»، «量词»، «比»، «不 و 没» را بپرس.", "I couldn't find a specific answer. Try: send a word to /dict, or ask about a topic like 了, 的, measure words, 比, 不 vs 没.", "Ich konnte keine konkrete Antwort finden. Versuche: ein Wort an /dict schicken, oder nach einem Thema wie 了, 的, Zählwörter, 比, 不 vs 没 fragen.")
S("ask_limit", "⏳ سهمیهٔ روزانهٔ پاسخ هوشمند تمام شد؛ فردا دوباره. (دیکشنری و یادداشت‌ها همچنان کار می‌کنند.)", "⏳ Today's AI answer quota is used up; try again tomorrow. (Dictionary and notes still work.)", "⏳ Das heutige KI-Kontingent ist aufgebraucht; versuche es morgen wieder. (Wörterbuch und Notizen funktionieren weiter.)")
S("grammar_note", "📘 <b>{title}</b>\n<code>{pattern}</code>\n\n{body}\n\n🈶 {zh}\n<i>{py}</i>\n{tr}", "📘 <b>{title}</b>\n<code>{pattern}</code>\n\n{body}\n\n🈶 {zh}\n<i>{py}</i>\n{tr}", "📘 <b>{title}</b>\n<code>{pattern}</code>\n\n{body}\n\n🈶 {zh}\n<i>{py}</i>\n{tr}")

# ---------- quiz / exercises ----------
S("quiz_head", "🧠 <b>تمرین</b> — سؤال {i}", "🧠 <b>Practice</b> — question {i}", "🧠 <b>Übung</b> — Frage {i}")
S("q_zh2m", "این واژه چه معنی دارد؟\n\n<b>{x}</b>", "What does this word mean?\n\n<b>{x}</b>", "Was bedeutet dieses Wort?\n\n<b>{x}</b>")
S("q_m2zh", "کدام واژهٔ چینی یعنی «{x}»؟", "Which Chinese word means “{x}”?", "Welches chinesische Wort bedeutet „{x}“?")
S("q_recog", "کدام نویسه با این تلفظ خوانده می‌شود: <b>{x}</b>؟", "Which character is read: <b>{x}</b>?", "Welches Zeichen wird so gelesen: <b>{x}</b>?")
S("q_tone", "لحن هجای <b>{x}</b> کدام است؟ (در واژهٔ {w})", "What is the tone of <b>{x}</b>? (in the word {w})", "Welchen Ton hat <b>{x}</b>? (im Wort {w})")
S("q_pytype", "پینیین این واژه را بنویس (با علامت لحن یا با عدد، مثلاً <code>ni3 hao3</code>):\n\n<b>{x}</b>", "Type the pinyin of this word (tone marks or numbers, e.g. <code>ni3 hao3</code>):\n\n<b>{x}</b>", "Tippe das Pinyin dieses Worts (Tonzeichen oder Zahlen, z. B. <code>ni3 hao3</code>):\n\n<b>{x}</b>")
S("q_fa2zh", "«{x}» را به چینی بنویس (نویسه‌های چینی):", "Write “{x}” in Chinese characters:", "Schreibe „{x}“ in chinesischen Zeichen:")
S("q_zh2fa", "معنی را بنویس:\n\n<b>{x}</b>", "Type the meaning:\n\n<b>{x}</b>", "Tippe die Bedeutung:\n\n<b>{x}</b>")
S("q_cloze", "جای خالی را پر کن:\n\n<b>{x}</b>\n{tr}", "Fill in the blank:\n\n<b>{x}</b>\n{tr}", "Fülle die Lücke:\n\n<b>{x}</b>\n{tr}")
S("q_build", "کلمه‌ها را به ترتیب درست بزن تا جمله ساخته شود:\n{tr}\n\n<b>{x}</b>", "Tap the words in the right order to build the sentence:\n{tr}\n\n<b>{x}</b>", "Tippe die Wörter in der richtigen Reihenfolge, um den Satz zu bilden:\n{tr}\n\n<b>{x}</b>")
S("q_listen", "🎧 گوش کن و معنی را انتخاب کن:", "🎧 Listen and choose the meaning:", "🎧 Hör zu und wähle die Bedeutung:")
S("q_listen_py", "🎧 گوش کن و پینیین را بنویس:", "🎧 Listen and type the pinyin:", "🎧 Hör zu und tippe das Pinyin:")
S("q_match", "🔗 جفت‌ها را وصل کن: اول یک واژهٔ چینی، بعد معنی‌اش را بزن.", "🔗 Match the pairs: tap a Chinese word, then its meaning.", "🔗 Ordne die Paare zu: tippe ein chinesisches Wort, dann seine Bedeutung.")
S("q_radical", "ریشهٔ (部首) نویسهٔ <b>{x}</b> کدام است؟", "What is the radical (部首) of <b>{x}</b>?", "Was ist das Radikal (部首) von <b>{x}</b>?")
S("q_strokes", "نویسهٔ <b>{x}</b> چند خط (stroke) دارد؟", "How many strokes does <b>{x}</b> have?", "Wie viele Striche hat <b>{x}</b>?")
S("q_custom", "❓ {x}", "❓ {x}", "❓ {x}")
S("q_shadow", "🗣 <b>تلفظ‌تمرین (سایه‌زنی)</b>\nاین جمله را بشنو، چند بار تکرار کن و بعد یک پیام صوتی بفرست:\n\n<b>{zh}</b>\n<i>{py}</i>\n{tr}", "🗣 <b>Shadowing practice</b>\nListen to this sentence, repeat it a few times, then send a voice message:\n\n<b>{zh}</b>\n<i>{py}</i>\n{tr}", "🗣 <b>Aussprache (Shadowing)</b>\nHör dir den Satz an, wiederhole ihn ein paar Mal und schick dann eine Sprachnachricht:\n\n<b>{zh}</b>\n<i>{py}</i>\n{tr}")
S("type_hint", "✍️ جوابت را تایپ کن (یا /cancel).", "✍️ Type your answer (or /cancel).", "✍️ Tippe deine Antwort (oder /cancel).")
S("ok_head", "✅ <b>درست!</b> +{xp} امتیاز", "✅ <b>Correct!</b> +{xp} XP", "✅ <b>Richtig!</b> +{xp} XP")
S("almost_head", "🟡 <b>تقریباً درست</b> +{xp} امتیاز", "🟡 <b>Almost</b> +{xp} XP", "🟡 <b>Fast richtig</b> +{xp} XP")
S("bad_head", "❌ <b>نادرست</b>", "❌ <b>Not quite</b>", "❌ <b>Leider falsch</b>")
S("right_answer", "✔️ جواب درست: <b>{a}</b>", "✔️ Correct answer: <b>{a}</b>", "✔️ Richtige Antwort: <b>{a}</b>")
S("your_answer", "✏️ جواب تو: {a}", "✏️ Your answer: {a}", "✏️ Deine Antwort: {a}")
S("explain_word", "ℹ️ {hz} <b>{py}</b> = {mean}", "ℹ️ {hz} <b>{py}</b> = {mean}", "ℹ️ {hz} <b>{py}</b> = {mean}")
S("fb_tone", "🎵 <b>خطای لحن</b> در هجای {i}: درست <b>{exp}</b> (لحن {et}) ولی تو لحن {gt} نوشتی ({got}). لحن‌ها معنی را عوض می‌کنند!", "🎵 <b>Tone mistake</b> in syllable {i}: should be <b>{exp}</b> (tone {et}) but you wrote tone {gt} ({got}). Tones change the meaning!", "🎵 <b>Tonfehler</b> in Silbe {i}: richtig <b>{exp}</b> (Ton {et}), du hast Ton {gt} geschrieben ({got}). Töne ändern die Bedeutung!")
S("fb_tone_missing", "🎵 حروف درست است ولی لحن را ننوشتی. درست: <b>{exp}</b>. همیشه لحن را همراه هجا بنویس (مثلاً ni3).", "🎵 The letters are right but you left out the tones. Correct: <b>{exp}</b>. Always write the tone with each syllable (e.g. ni3).", "🎵 Die Buchstaben stimmen, aber die Töne fehlen. Richtig: <b>{exp}</b>. Schreibe den Ton immer mit (z. B. ni3).")
S("fb_initial", "🔤 <b>خطای حرف آغازین</b> در هجای {i}: «{exp}» درست است نه «{got}». {tip}", "🔤 <b>Initial mistake</b> in syllable {i}: it is “{exp}”, not “{got}”. {tip}", "🔤 <b>Anlautfehler</b> in Silbe {i}: richtig ist „{exp}“, nicht „{got}“. {tip}")
S("fb_final", "🔤 <b>خطای وان</b> در هجای {i}: «{exp}» درست است نه «{got}». {tip}", "🔤 <b>Final mistake</b> in syllable {i}: it is “{exp}”, not “{got}”. {tip}", "🔤 <b>Finale-Fehler</b> in Silbe {i}: richtig ist „{exp}“, nicht „{got}“. {tip}")
S("fb_letters", "🔤 هجای {i}: «{exp}» درست است نه «{got}».", "🔤 Syllable {i}: it is “{exp}”, not “{got}”.", "🔤 Silbe {i}: richtig ist „{exp}“, nicht „{got}“.")
S("fb_count", "🔢 تعداد هجاها درست نیست: باید {n} هجا باشد.", "🔢 The number of syllables is wrong: there should be {n}.", "🔢 Die Silbenzahl stimmt nicht: Es sollten {n} sein.")
S("fb_typed_pinyin", "📝 تو پینیین نوشتی ولی اینجا نویسهٔ چینی می‌خواهم.", "📝 You typed pinyin, but here I need Chinese characters.", "📝 Du hast Pinyin getippt, hier brauche ich aber chinesische Zeichen.")
S("fb_typed_hanzi", "📝 تو نویسهٔ چینی نوشتی ولی اینجا پینیین می‌خواهم.", "📝 You typed Chinese characters, but here I need pinyin.", "📝 Du hast chinesische Zeichen getippt, hier brauche ich aber Pinyin.")
S("fb_wrong_char", "🈶 نویسه‌های اشتباه: {chars}", "🈶 Wrong characters: {chars}", "🈶 Falsche Zeichen: {chars}")
S("fb_llm", "🤖 {t}", "🤖 {t}", "🤖 {t}")
S("fb_flex", "💬 ممکن است جملهٔ تو هم درست باشد؛ من با یک پاسخ آماده مقایسه کردم. برای بررسی انعطاف‌پذیر، مدیر باید هوش مصنوعی را فعال کند.", "💬 Your answer may also be valid; I compared against a fixed answer. For flexible grading the admin must enable the AI.", "💬 Deine Antwort könnte auch richtig sein; ich habe mit einer festen Antwort verglichen. Für flexible Bewertung muss der Admin die KI aktivieren.")
S("fb_close", "📏 خیلی نزدیک بود.", "📏 Very close.", "📏 Sehr nah dran.")
S("q_done", "🏁 <b>تمرین تمام شد</b>\n✅ {ok} از {n} درست\n⭐ +{xp} امتیاز", "🏁 <b>Practice finished</b>\n✅ {ok} of {n} correct\n⭐ +{xp} XP", "🏁 <b>Übung beendet</b>\n✅ {ok} von {n} richtig\n⭐ +{xp} XP")
S("match_ok", "✅ جفت درست!", "✅ Correct pair!", "✅ Richtiges Paar!")
S("match_bad", "❌ این جفت نیست.", "❌ Not a pair.", "❌ Kein Paar.")
S("match_done", "🎉 همهٔ جفت‌ها وصل شد! خطاها: {n}", "🎉 All pairs matched! Mistakes: {n}", "🎉 Alle Paare zugeordnet! Fehler: {n}")
S("no_session", "این تمرین قدیمی شده؛ یکی تازه شروع کن.", "That exercise has expired; start a new one.", "Diese Übung ist abgelaufen; starte eine neue.")
S("shadow_nostt", "🎤 پیام صوتی‌ات را گرفتم! تشخیص خودکار تلفظ فعلاً فعال نیست (به مدل گفتار‌به‌متن نیاز دارد). خودت را با صدای مدل مقایسه کن:\n1) دوباره 🔊 را بزن و گوش کن\n2) صدای خودت را پخش کن\n3) لحن‌ها را یکی‌یکی چک کن: {py}\n<i>مدیر می‌تواند با CHINESE_LLM_STT_MODEL بازخورد خودکار را روشن کند.</i>", "🎤 Got your voice message! Automatic pronunciation checking is not enabled (it needs a speech-to-text model). Compare yourself with the model voice:\n1) tap 🔊 and listen again\n2) play your recording\n3) check the tones one by one: {py}\n<i>The admin can enable automatic feedback with CHINESE_LLM_STT_MODEL.</i>", "🎤 Sprachnachricht erhalten! Die automatische Ausspracheprüfung ist nicht aktiviert (sie braucht ein Speech-to-Text-Modell). Vergleiche selbst mit der Modellstimme:\n1) 🔊 antippen und erneut hören\n2) deine Aufnahme abspielen\n3) die Töne einzeln prüfen: {py}\n<i>Der Admin kann mit CHINESE_LLM_STT_MODEL automatisches Feedback aktivieren.</i>")
S("shadow_res", "🎤 من شنیدم: «{heard}»\nهدف: «{target}»\n{verdict}", "🎤 I heard: “{heard}”\nTarget: “{target}”\n{verdict}", "🎤 Ich habe gehört: „{heard}“\nZiel: „{target}“\n{verdict}")
S("shadow_good", "✅ عالی! تلفظت قابل فهم بود.", "✅ Great! Your pronunciation was understood.", "✅ Super! Deine Aussprache wurde verstanden.")
S("shadow_diff", "🔁 کمی فرق داشت؛ دوباره گوش کن و تکرار کن. (تشخیص گفتار دقیق نیست و فقط راهنماست.)", "🔁 Slightly different; listen again and repeat. (Speech recognition is approximate, only a guide.)", "🔁 Etwas anders; hör nochmal zu und wiederhole. (Spracherkennung ist ungenau, nur ein Anhaltspunkt.)")
S("tts_fail", "🔇 صدا فعلاً ساخته نشد (سرویس صدا در دسترس نیست). متن: {t}", "🔇 Couldn't generate audio right now (TTS unavailable). Text: {t}", "🔇 Audio konnte gerade nicht erzeugt werden (TTS nicht verfügbar). Text: {t}")

# ---------- today / review / progress ----------
S("today", "📅 <b>درس امروز</b> — {date}\n\n{l1} لغت جدید: {nw}/{nwt}\n{l2} مرور سررسیده: {due}\n{l3} تمرین: {pr}/{prt} پاسخ\n\n🔥 رگه (streak): {streak} روز", "📅 <b>Today's lesson</b> — {date}\n\n{l1} New words: {nw}/{nwt}\n{l2} Due reviews: {due}\n{l3} Practice: {pr}/{prt} answers\n\n🔥 Streak: {streak} days", "📅 <b>Heutige Lektion</b> — {date}\n\n{l1} Neue Wörter: {nw}/{nwt}\n{l2} Fällige Wiederholungen: {due}\n{l3} Übung: {pr}/{prt} Antworten\n\n🔥 Serie: {streak} Tage")
S("b_t_new", "📖 لغت جدید", "📖 New words", "📖 Neue Wörter")
S("b_t_rev", "🔁 مرور ({n})", "🔁 Review ({n})", "🔁 Wiederholen ({n})")
S("b_t_prac", "🧠 تمرین", "🧠 Practice", "🧠 Üben")
S("b_t_tip", "💡 نکتهٔ امروز", "💡 Tip of the day", "💡 Tipp des Tages")
S("today_done", "🎉 هدف امروز کامل شد! آفرین. فردا هم بیا تا رگه‌ات حفظ شود 🔥", "🎉 Today's goal is complete! Well done. Come back tomorrow to keep your streak 🔥", "🎉 Das heutige Ziel ist erreicht! Gut gemacht. Komm morgen wieder, um deine Serie zu halten 🔥")
S("review_none", "✨ هیچ کارتی برای مرور سررسید نشده. بعداً برگرد یا لغت جدید بیاموز.", "✨ No cards are due for review. Come back later or learn new words.", "✨ Keine Karten zur Wiederholung fällig. Komm später wieder oder lerne neue Wörter.")
S("review_front", "🔁 <b>مرور</b> ({left} مانده) — جعبه {box}\n\n{hz}\n\nمعنی و تلفظ را به یاد می‌آوری؟", "🔁 <b>Review</b> ({left} left) — box {box}\n\n{hz}\n\nDo you remember meaning and pronunciation?", "🔁 <b>Wiederholung</b> ({left} übrig) — Box {box}\n\n{hz}\n\nErinnerst du dich an Bedeutung und Aussprache?")
S("review_done", "🏁 مرور تمام شد! {n} کارت.\n📦 جعبه‌ها: {boxes}", "🏁 Review done! {n} cards.\n📦 Boxes: {boxes}", "🏁 Wiederholung beendet! {n} Karten.\n📦 Boxen: {boxes}")
S("box_moved", "📦 جعبه {b} — مرور بعدی: {when}", "📦 Box {b} — next review: {when}", "📦 Box {b} — nächste Wiederholung: {when}")
S("when_min", "{n} دقیقه دیگر", "in {n} min", "in {n} Min.")
S("when_day", "{n} روز دیگر", "in {n} days", "in {n} Tagen")
S("progress", "📊 <b>پیشرفت تو</b>\n\n👤 سطح: <b>{level}</b>\n⭐ امتیاز: <b>{xp}</b>\n🔥 رگه: <b>{streak}</b> روز (بهترین: {best})\n🎯 دقت: <b>{acc}٪</b> ({ok}/{tot})\n\n📚 لغات در حال یادگیری: <b>{cards}</b> • تسلط‌یافته: <b>{mast}</b>\n📦 جعبه‌ها: {boxes}\n📈 HSK 1: {p1} • HSK 2: {p2} • HSK 3: {p3}\n❗ اشتباهات مرورنشده: <b>{mist}</b>\n🔁 مرورهای سررسیده: <b>{due}</b>",
  "📊 <b>Your progress</b>\n\n👤 Level: <b>{level}</b>\n⭐ XP: <b>{xp}</b>\n🔥 Streak: <b>{streak}</b> days (best: {best})\n🎯 Accuracy: <b>{acc}%</b> ({ok}/{tot})\n\n📚 Words in learning: <b>{cards}</b> • mastered: <b>{mast}</b>\n📦 Boxes: {boxes}\n📈 HSK 1: {p1} • HSK 2: {p2} • HSK 3: {p3}\n❗ Unreviewed mistakes: <b>{mist}</b>\n🔁 Reviews due: <b>{due}</b>",
  "📊 <b>Dein Fortschritt</b>\n\n👤 Niveau: <b>{level}</b>\n⭐ XP: <b>{xp}</b>\n🔥 Serie: <b>{streak}</b> Tage (Rekord: {best})\n🎯 Genauigkeit: <b>{acc}%</b> ({ok}/{tot})\n\n📚 Wörter im Lernen: <b>{cards}</b> • gemeistert: <b>{mast}</b>\n📦 Boxen: {boxes}\n📈 HSK 1: {p1} • HSK 2: {p2} • HSK 3: {p3}\n❗ Nicht wiederholte Fehler: <b>{mist}</b>\n🔁 Fällige Wiederholungen: <b>{due}</b>")
S("b_mistakes", "❗ مرور اشتباهات", "❗ Review mistakes", "❗ Fehler wiederholen")
S("mistakes_none", "👏 اشتباه مرورنشده‌ای نداری!", "👏 You have no unreviewed mistakes!", "👏 Du hast keine unwiederholten Fehler!")
S("mistakes_head", "❗ <b>اشتباهات اخیر تو</b>:", "❗ <b>Your recent mistakes</b>:", "❗ <b>Deine letzten Fehler</b>:")
S("mistake_line", "{hz} <b>{py}</b> — {mean}\n   ✏️ {given} → ✔️ {exp}", "{hz} <b>{py}</b> — {mean}\n   ✏️ {given} → ✔️ {exp}", "{hz} <b>{py}</b> — {mean}\n   ✏️ {given} → ✔️ {exp}")
S("tip_head", "💡 <b>نکتهٔ امروز</b>", "💡 <b>Tip of the day</b>", "💡 <b>Tipp des Tages</b>")

# ---------- alphabet ----------
S("alpha_menu", "🔤 <b>آوا و حروف چینی</b>\nیکی را انتخاب کن:", "🔤 <b>Sounds & Chinese characters</b>\nChoose one:", "🔤 <b>Laute & chinesische Zeichen</b>\nWähle eines:")
S("b_a_init", "🅱️ حروف آغازین", "🅱️ Initials", "🅱️ Anlaute")
S("b_a_final", "🅰️ وان‌ها", "🅰️ Finals", "🅰️ Finale")
S("b_a_tones", "🎵 لحن‌ها", "🎵 Tones", "🎵 Töne")
S("b_a_rules", "✏️ قواعد املا", "✏️ Spelling rules", "✏️ Schreibregeln")
S("b_a_strokes", "🖌 خط‌ها و ترتیب نوشتن", "🖌 Strokes & stroke order", "🖌 Striche & Strichfolge")
S("b_a_radicals", "🧱 ریشه‌های پرکاربرد", "🧱 Common radicals", "🧱 Häufige Radikale")
S("b_a_sandhi", "🔀 تغییر لحن", "🔀 Tone changes", "🔀 Tonwechsel")
S("b_a_tips", "🎯 نکات تلفظ", "🎯 Pronunciation tips", "🎯 Aussprachetipps")
S("b_a_culture", "🏮 فرهنگ", "🏮 Culture", "🏮 Kultur")
S("b_a_idiom", "📜 ضرب‌المثل (成语)", "📜 Idioms (成语)", "📜 Redewendungen (成语)")
S("b_a_grammar", "📘 دستور زبان", "📘 Grammar", "📘 Grammatik")
S("b_a_practice", "🧠 تمرین آوا", "🧠 Sound practice", "🧠 Lautübung")
S("init_head", "🅱️ <b>حروف آغازین (声母)</b> — {grp}\nبرای شنیدن تلفظ، دکمهٔ حرف را بزن.\n\n{lines}", "🅱️ <b>Initials (声母)</b> — {grp}\nTap a letter to hear it.\n\n{lines}", "🅱️ <b>Anlaute (声母)</b> — {grp}\nTippe auf einen Buchstaben, um ihn zu hören.\n\n{lines}")
S("final_head", "🅰️ <b>وان‌ها (韵母)</b> — {grp}\nبرای شنیدن، دکمه را بزن.\n\n{lines}", "🅰️ <b>Finals (韵母)</b> — {grp}\nTap to hear.\n\n{lines}", "🅰️ <b>Finale (韵母)</b> — {grp}\nZum Hören antippen.\n\n{lines}")
S("init_item", "<b>{l}</b> — {hz} <b>{py}</b> ({mean})\n   💡 {hint}", "<b>{l}</b> — {hz} <b>{py}</b> ({mean})\n   💡 {hint}", "<b>{l}</b> — {hz} <b>{py}</b> ({mean})\n   💡 {hint}")
S("final_item", "<b>{l}</b> — {hz} <b>{py}</b> ({mean})", "<b>{l}</b> — {hz} <b>{py}</b> ({mean})", "<b>{l}</b> — {hz} <b>{py}</b> ({mean})")
S("tones_head", "🎵 <b>چهار لحن + لحن خنثی</b>\nچینی زبان آهنگین است: یک هجا با لحن‌های مختلف، معنی‌های مختلف دارد.\n\n{lines}\n\n<b>قاعدهٔ جای علامت:</b>\n{rules}", "🎵 <b>Four tones + neutral</b>\nChinese is tonal: the same syllable with different tones means different things.\n\n{lines}\n\n<b>Where the mark goes:</b>\n{rules}", "🎵 <b>Vier Töne + neutral</b>\nChinesisch ist eine Tonsprache: dieselbe Silbe mit anderem Ton bedeutet etwas anderes.\n\n{lines}\n\n<b>Wohin das Zeichen kommt:</b>\n{rules}")
S("rules_head", "✏️ <b>قواعد املای پینیین</b>\n\n{rules}", "✏️ <b>Pinyin spelling rules</b>\n\n{rules}", "✏️ <b>Pinyin-Schreibregeln</b>\n\n{rules}")
S("sandhi_head", "🔀 <b>تغییر لحن (变调)</b>\n\n{rules}", "🔀 <b>Tone changes (变调)</b>\n\n{rules}", "🔀 <b>Tonwechsel (变调)</b>\n\n{rules}")
S("strokes_head", "🖌 <b>خط‌های پایه (笔画)</b>\n\n{lines}\n\n<b>قانون‌های ترتیب نوشتن:</b>\n{rules}\n\n✍️ ترتیب خط هر نویسه را در کارت لغت با «✍️» ببین، یا بنویس: <code>/stroke 学</code>", "🖌 <b>Basic strokes (笔画)</b>\n\n{lines}\n\n<b>Stroke-order rules:</b>\n{rules}\n\n✍️ See any character's order with “✍️” on a word card, or type <code>/stroke 学</code>", "🖌 <b>Grundstriche (笔画)</b>\n\n{lines}\n\n<b>Regeln der Strichfolge:</b>\n{rules}\n\n✍️ Die Strichfolge siehst du mit „✍️“ auf der Wortkarte, oder tippe <code>/stroke 学</code>")
S("radicals_head", "🧱 <b>ریشه‌های پرکاربرد (部首)</b> — صفحه {p}/{pages}\n\n{lines}", "🧱 <b>Common radicals (部首)</b> — page {p}/{pages}\n\n{lines}", "🧱 <b>Häufige Radikale (部首)</b> — Seite {p}/{pages}\n\n{lines}")
S("tips_head", "🎯 <b>نکتهٔ تلفظ</b> ({i}/{n})\n\n{t}", "🎯 <b>Pronunciation tip</b> ({i}/{n})\n\n{t}", "🎯 <b>Aussprachetipp</b> ({i}/{n})\n\n{t}")
S("culture_head", "🏮 <b>{title}</b>\n\n{body}", "🏮 <b>{title}</b>\n\n{body}", "🏮 <b>{title}</b>\n\n{body}")
S("idiom", "📜 <b>{zh}</b>\n<i>{py}</i>\n\n{mean}\n🔤 {lit}", "📜 <b>{zh}</b>\n<i>{py}</i>\n\n{mean}\n🔤 {lit}", "📜 <b>{zh}</b>\n<i>{py}</i>\n\n{mean}\n🔤 {lit}")
S("grammar_list", "📘 <b>دستور زبان</b> — یک مبحث را انتخاب کن:", "📘 <b>Grammar</b> — choose a topic:", "📘 <b>Grammatik</b> — wähle ein Thema:")

# ---------- reader ----------
S("reader_list", "📚 <b>داستان‌های کوتاه</b> — سطح خودت یا پایین‌تر:", "📚 <b>Short stories</b> — your level or lower:", "📚 <b>Kurztexte</b> — dein Niveau oder darunter:")
S("reader_head", "📚 <b>{title}</b>  (HSK {lv})\n\n{lines}", "📚 <b>{title}</b>  (HSK {lv})\n\n{lines}", "📚 <b>{title}</b>  (HSK {lv})\n\n{lines}")
S("b_py_on", "🔤 نمایش پینیین", "🔤 Show pinyin", "🔤 Pinyin zeigen")
S("b_py_off", "🔤 پنهان کردن پینیین", "🔤 Hide pinyin", "🔤 Pinyin ausblenden")
S("b_tr_on", "🌐 نمایش ترجمه", "🌐 Show translation", "🌐 Übersetzung zeigen")
S("b_tr_off", "🌐 پنهان کردن ترجمه", "🌐 Hide translation", "🌐 Übersetzung ausblenden")

# ---------- settings / methods ----------
S("settings", "⚙️ <b>تنظیمات</b>\n\n🌐 زبان ربات: <b>{ui}</b>\n💬 زبان توضیحات: <b>{expl}</b>\n📶 سطح: <b>{level}</b>\n🎯 هدف روزانه: <b>{goal}</b> پاسخ\n🔁 الگوریتم مرور: <b>{srs}</b>\n⏰ یادآور: <b>{remind}</b>\n🕒 منطقهٔ زمانی: <b>{tz}</b>\n🧰 روش‌ها: <b>{methods}</b>", "⚙️ <b>Settings</b>\n\n🌐 Bot language: <b>{ui}</b>\n💬 Explanation language: <b>{expl}</b>\n📶 Level: <b>{level}</b>\n🎯 Daily goal: <b>{goal}</b> answers\n🔁 Review algorithm: <b>{srs}</b>\n⏰ Reminder: <b>{remind}</b>\n🕒 Time zone: <b>{tz}</b>\n🧰 Methods: <b>{methods}</b>", "⚙️ <b>Einstellungen</b>\n\n🌐 Botsprache: <b>{ui}</b>\n💬 Erklärungssprache: <b>{expl}</b>\n📶 Niveau: <b>{level}</b>\n🎯 Tagesziel: <b>{goal}</b> Antworten\n🔁 Wiederholungs-Algorithmus: <b>{srs}</b>\n⏰ Erinnerung: <b>{remind}</b>\n🕒 Zeitzone: <b>{tz}</b>\n🧰 Methoden: <b>{methods}</b>")
S("b_s_ui", "🌐 زبان ربات", "🌐 Bot language", "🌐 Botsprache")
S("b_s_expl", "💬 زبان توضیحات", "💬 Explanations", "💬 Erklärungen")
S("b_s_level", "📶 سطح", "📶 Level", "📶 Niveau")
S("b_s_goal", "🎯 هدف روزانه", "🎯 Daily goal", "🎯 Tagesziel")
S("b_s_srs", "🔁 الگوریتم مرور", "🔁 Algorithm", "🔁 Algorithmus")
S("b_s_remind", "⏰ یادآور", "⏰ Reminder", "⏰ Erinnerung")
S("b_s_tz", "🕒 منطقهٔ زمانی", "🕒 Time zone", "🕒 Zeitzone")
S("b_s_methods", "🧰 روش‌های یادگیری", "🧰 Learning methods", "🧰 Lernmethoden")
S("b_s_del", "🗑 حذف داده‌های من", "🗑 Delete my data", "🗑 Meine Daten löschen")
S("expl_auto", "خودکار (زبان پیامت)", "Auto (language of your message)", "Automatisch (Sprache deiner Nachricht)")
S("lang_fa", "فارسی 🇮🇷", "Persian 🇮🇷", "Persisch 🇮🇷")
S("lang_en", "English 🇬🇧", "English 🇬🇧", "Englisch 🇬🇧")
S("lang_de", "Deutsch 🇩🇪", "German 🇩🇪", "Deutsch 🇩🇪")
S("srs_leitner", "لایتنر (جعبه ۱–۵)", "Leitner (boxes 1–5)", "Leitner (Boxen 1–5)")
S("srs_sm2", "SM-2", "SM-2", "SM-2")
S("srs_info", "🔁 <b>الگوریتم مرور</b>\n\n📦 <b>لایتنر:</b> ۵ جعبه؛ جواب درست = جعبهٔ بعدی، غلط = برگشت به جعبهٔ ۱.\nفاصله: جعبه ۱: ۱ روز • ۲: ۲ روز • ۳: ۴ روز • ۴: ۸ روز • ۵: ۱۶ روز (و بعد ۳۰ روز = تسلط).\n\n🧮 <b>SM-2:</b> فاصله بر اساس «سهولت» هر کارت خودکار تنظیم می‌شود (۱ روز، ۶ روز، سپس ضرب در ضریب).", "🔁 <b>Review algorithm</b>\n\n📦 <b>Leitner:</b> 5 boxes; correct = next box, wrong = back to box 1.\nIntervals: box 1: 1 day • 2: 2 days • 3: 4 days • 4: 8 days • 5: 16 days (then 30 days = mastered).\n\n🧮 <b>SM-2:</b> intervals adapt to each card's “ease” (1 day, 6 days, then × ease).", "🔁 <b>Wiederholungs-Algorithmus</b>\n\n📦 <b>Leitner:</b> 5 Boxen; richtig = nächste Box, falsch = zurück in Box 1.\nIntervalle: Box 1: 1 Tag • 2: 2 Tage • 3: 4 Tage • 4: 8 Tage • 5: 16 Tage (danach 30 Tage = gemeistert).\n\n🧮 <b>SM-2:</b> Intervalle passen sich der „Leichtigkeit“ jeder Karte an (1 Tag, 6 Tage, dann × Faktor).")
S("pick_goal", "🎯 هدف روزانه (تعداد پاسخ):", "🎯 Daily goal (number of answers):", "🎯 Tagesziel (Anzahl Antworten):")
S("pick_tz", "🕒 منطقهٔ زمانی را انتخاب کن:", "🕒 Choose your time zone:", "🕒 Wähle deine Zeitzone:")
S("pick_remind", "⏰ <b>یادآور روزانه</b>\nپیش‌فرض خاموش است. ساعت را انتخاب کن تا هر روز یک پیام کوتاه بگیری (به وقت منطقهٔ زمانی تو).", "⏰ <b>Daily reminder</b>\nOff by default. Pick a time to get one short message a day (in your time zone).", "⏰ <b>Tägliche Erinnerung</b>\nStandardmäßig aus. Wähle eine Uhrzeit für eine kurze Nachricht pro Tag (in deiner Zeitzone).")
S("b_off", "⛔ خاموش", "⛔ Off", "⛔ Aus")
S("b_remind_custom", "✏️ ساعت دلخواه", "✏️ Custom time", "✏️ Eigene Uhrzeit")
S("remind_type", "ساعت را به صورت HH:MM بفرست (مثلاً 19:30).", "Send the time as HH:MM (e.g. 19:30).", "Schick die Uhrzeit als HH:MM (z. B. 19:30).")
S("remind_set", "✅ یادآور روزانه روی {t} ({tz}) تنظیم شد.", "✅ Daily reminder set to {t} ({tz}).", "✅ Tägliche Erinnerung auf {t} ({tz}) gestellt.")
S("remind_cleared", "⛔ یادآور خاموش شد.", "⛔ Reminder turned off.", "⛔ Erinnerung ausgeschaltet.")
S("bad_time", "⚠️ ساعت نامعتبر است؛ مثل 19:30 بنویس.", "⚠️ Invalid time; write it like 19:30.", "⚠️ Ungültige Uhrzeit; schreibe sie wie 19:30.")
S("remind_msg", "⏰ وقت چینی‌خواندن است! 🇨🇳\n📚 {due} مرور سررسیده • 🔥 رگه: {streak} روز\nیک درس کوتاه امروز را بزن 👇", "⏰ Time for Chinese! 🇨🇳\n📚 {due} reviews due • 🔥 streak: {streak} days\nTap today's short lesson 👇", "⏰ Zeit für Chinesisch! 🇨🇳\n📚 {due} Wiederholungen fällig • 🔥 Serie: {streak} Tage\nTippe auf die kurze Lektion von heute 👇")
S("methods_head", "🧰 <b>روش‌های یادگیری</b>\nروش‌هایی را که دوست داری روشن کن؛ تمرین‌های تو از همین‌ها ساخته می‌شود. برای شروع فوری هر روش، ▶️ را بزن.\nاگر هیچ‌کدام روشن نباشد، ترکیب متنوعی داده می‌شود.", "🧰 <b>Learning methods</b>\nSwitch on the methods you like; your practice is built from them. Tap ▶️ to start a method right away.\nIf none is on, you get a varied mix.", "🧰 <b>Lernmethoden</b>\nSchalte die Methoden ein, die du magst; deine Übungen werden daraus gebaut. Mit ▶️ startest du eine Methode sofort.\nIst keine an, bekommst du eine gemischte Auswahl.")
S("m_flashcards", "🃏 فلش‌کارت", "🃏 Flashcards", "🃏 Karteikarten")
S("m_mnemonic", "💡 یادیار و داستان", "💡 Mnemonics & stories", "💡 Eselsbrücken & Geschichten")
S("m_radicals", "🧱 ریشه و اجزا", "🧱 Radicals & components", "🧱 Radikale & Bestandteile")
S("m_strokes", "✍️ تمرین نوشتن", "✍️ Writing & strokes", "✍️ Schreiben & Striche")
S("m_dictation", "🎧 دیکته و شنیداری", "🎧 Listening & dictation", "🎧 Hören & Diktat")
S("m_pinyin", "⌨️ تایپ پینیین", "⌨️ Pinyin typing", "⌨️ Pinyin tippen")
S("m_building", "🧩 جمله‌سازی", "🧩 Sentence building", "🧩 Sätze bauen")
S("m_shadowing", "🗣 سایه‌زنی و تلفظ", "🗣 Shadowing & pronunciation", "🗣 Shadowing & Aussprache")
S("m_cloze", "🕳 جای خالی", "🕳 Cloze (fill the blank)", "🕳 Lückentext")
S("m_matching", "🔗 بازی جفت‌یابی", "🔗 Matching game", "🔗 Zuordnungsspiel")
S("m_review", "🔁 مرور روزانه", "🔁 Daily review", "🔁 Tägliche Wiederholung")
S("m_mock", "📝 آزمون آزمایشی HSK", "📝 HSK mock test", "📝 HSK-Probetest")
S("m_reader", "📚 متن‌های کوتاه", "📚 Graded readers", "📚 Lesetexte")
S("mock_intro", "📝 <b>آزمون آزمایشی HSK {lv}</b>\n۱۰ سؤال ترکیبی؛ نمره در پایان. زمان محدود نیست. موفق باشی!", "📝 <b>HSK {lv} mock test</b>\n10 mixed questions; score at the end. No time limit. Good luck!", "📝 <b>HSK-{lv}-Probetest</b>\n10 gemischte Fragen; Ergebnis am Ende. Kein Zeitlimit. Viel Erfolg!")
S("mock_done", "📝 <b>نتیجهٔ آزمون HSK {lv}</b>\n✅ {ok} از {n} → <b>{pct}٪</b>\n{grade}", "📝 <b>HSK {lv} mock result</b>\n✅ {ok} of {n} → <b>{pct}%</b>\n{grade}", "📝 <b>HSK-{lv}-Ergebnis</b>\n✅ {ok} von {n} → <b>{pct}%</b>\n{grade}")
S("grade_hi", "🏆 عالی! آمادهٔ سطح بعدی هستی.", "🏆 Excellent! You're ready for the next level.", "🏆 Ausgezeichnet! Du bist bereit für das nächste Niveau.")
S("grade_mid", "👍 خوب است؛ اشتباهاتت را مرور کن.", "👍 Good; review your mistakes.", "👍 Gut; wiederhole deine Fehler.")
S("grade_lo", "💪 ادامه بده؛ مرور و تمرین بیشتر لازم است.", "💪 Keep going; more review and practice needed.", "💪 Weiter so; mehr Wiederholung und Übung nötig.")
S("del_ask", "🗑 همهٔ پیشرفت و تنظیمات تو پاک شود؟ این کار برگشت‌پذیر نیست.", "🗑 Delete all your progress and settings? This cannot be undone.", "🗑 Deinen gesamten Fortschritt und alle Einstellungen löschen? Das kann nicht rückgängig gemacht werden.")
S("del_done", "✅ داده‌های تو پاک شد. هر وقت خواستی با /start برگرد.", "✅ Your data was deleted. Come back any time with /start.", "✅ Deine Daten wurden gelöscht. Komm jederzeit mit /start zurück.")
S("saved", "✅ ذخیره شد.", "✅ Saved.", "✅ Gespeichert.")
S("stroke_usage", "یک نویسهٔ چینی بعد از دستور بنویس: <code>/stroke 学</code>", "Write a Chinese character after the command: <code>/stroke 学</code>", "Schreibe ein chinesisches Zeichen hinter den Befehl: <code>/stroke 学</code>")
S("word_none", "لغتی پیدا نشد.", "No word found.", "Kein Wort gefunden.")
S("owner_bound", "👑 شما به‌عنوان مالک ربات شناخته شدید. پنل: /admin", "👑 You are recognised as the bot owner. Panel: /admin", "👑 Du wurdest als Eigentümer des Bots erkannt. Panel: /admin")

# ---------- groups ----------
S("g_intro", "👋 سلام به همه! من <b>{name}</b> هستم، معلم چینی (ماندارین) 🇨🇳\n\n<b>چه کارهایی می‌کنم؟</b>\n🧠 /quiz — یک تمرین برای همهٔ گروه؛ اولین جواب درست امتیاز می‌گیرد\n📖 /word — واژهٔ روز با تلفظ و معنی\n🔍 /dict <i>واژه</i> — دیکشنری\n💬 /ask <i>سؤال</i> — دستور زبان و کاربرد\n🏆 /top — جدول امتیازات گروه\n\n<b>چطور با من حرف بزنیم؟</b>\n• با دستورها (مثلاً <code>/quiz@{bot}</code>)\n• من را منشن کنید: <code>@{bot} 学校</code>\n• روی پیام‌های من ریپلای بزنید\n\n<b>مدیران گروه:</b> با /settings زبان، سطح، «واژهٔ روز» و روشن/خاموش بودن من را تنظیم کنید.\n🔒 پیشرفت شخصی هر نفر فقط در چت خصوصی خودش ثبت می‌شود و از گروه جداست.\n\n👇 برای یادگیری شخصی، چت خصوصی را باز کنید:",
  "👋 Hello everyone! I'm <b>{name}</b>, a Mandarin Chinese teacher 🇨🇳\n\n<b>What I do:</b>\n🧠 /quiz — one exercise for the whole group; first correct answer scores\n📖 /word — word of the day with pronunciation and meaning\n🔍 /dict <i>word</i> — dictionary\n💬 /ask <i>question</i> — grammar & usage\n🏆 /top — group leaderboard\n\n<b>How to talk to me:</b>\n• Commands (e.g. <code>/quiz@{bot}</code>)\n• Mention me: <code>@{bot} 学校</code>\n• Reply to my messages\n\n<b>Group admins:</b> use /settings to set language, level, “word of the day” and to enable/disable me.\n🔒 Each person's personal progress is stored only in their own private chat, separate from the group.\n\n👇 For personal learning, open the private chat:",
  "👋 Hallo zusammen! Ich bin <b>{name}</b>, ein Mandarin-Lehrer 🇨🇳\n\n<b>Was ich kann:</b>\n🧠 /quiz — eine Übung für die ganze Gruppe; die erste richtige Antwort punktet\n📖 /word — Wort des Tages mit Aussprache und Bedeutung\n🔍 /dict <i>Wort</i> — Wörterbuch\n💬 /ask <i>Frage</i> — Grammatik & Gebrauch\n🏆 /top — Gruppen-Rangliste\n\n<b>So sprecht ihr mit mir:</b>\n• Befehle (z. B. <code>/quiz@{bot}</code>)\n• Erwähnt mich: <code>@{bot} 学校</code>\n• Antwortet auf meine Nachrichten\n\n<b>Gruppen-Admins:</b> mit /settings Sprache, Niveau, „Wort des Tages“ und An/Aus einstellen.\n🔒 Der persönliche Fortschritt jeder Person wird nur im eigenen Privatchat gespeichert, getrennt von der Gruppe.\n\n👇 Für persönliches Lernen den Privatchat öffnen:")
S("g_admin_thanks", "🙏 ممنون که من را مدیر کردید!\n\n<b>حالا چه کارهای بیشتری می‌توانم؟</b>\n👀 همهٔ پیام‌های گروه را می‌بینم، پس وقتی صدایم کنند (منشن/ریپلای) بدون نیاز به دستور دقیق هم جواب می‌دهم\n📌 «واژهٔ روز» را می‌توانم سنجاق کنم\n🧹 پیام‌های تمرین قدیمی را مرتب می‌کنم\n\nتنظیمات: /settings (فقط مدیران).", "🙏 Thanks for making me an admin!\n\n<b>What can I do more now?</b>\n👀 I can see all group messages, so I answer when addressed (mention/reply) without exact command syntax\n📌 I can pin the “word of the day”\n🧹 I can tidy old exercise messages\n\nSettings: /settings (admins only).", "🙏 Danke, dass ihr mich zum Admin gemacht habt!\n\n<b>Was kann ich jetzt zusätzlich?</b>\n👀 Ich sehe alle Gruppennachrichten und antworte daher auch ohne exakte Befehlssyntax, wenn man mich anspricht (Erwähnung/Antwort)\n📌 Ich kann das „Wort des Tages“ anpinnen\n🧹 Ich kann alte Übungsnachrichten aufräumen\n\nEinstellungen: /settings (nur Admins).")
S("g_privacy_note", "ℹ️ اگر حالت حریم خصوصی (privacy mode) روشن باشد فقط دستورها، منشن‌ها و ریپلای‌ها را می‌بینم. برای دیدن همهٔ پیام‌ها مرا ادمین کنید.", "ℹ️ With privacy mode on, I only see commands, mentions and replies. To see all messages, make me a group admin.", "ℹ️ Bei aktivem Datenschutzmodus sehe ich nur Befehle, Erwähnungen und Antworten. Um alle Nachrichten zu sehen, macht mich zum Gruppen-Admin.")
S("g_disabled", "⛔ این ربات در این گروه توسط مدیران خاموش شده است.", "⛔ The bot is switched off in this group by the admins.", "⛔ Der Bot wurde in dieser Gruppe von den Admins ausgeschaltet.")
S("g_only_admin", "🔒 فقط مدیران گروه می‌توانند این را تغییر دهند.", "🔒 Only group admins can change this.", "🔒 Nur Gruppen-Admins können das ändern.")
S("g_settings", "⚙️ <b>تنظیمات گروه</b>\n\n🌐 زبان پیام‌ها: <b>{ui}</b>\n💬 زبان توضیحات: <b>{expl}</b>\n📶 سطح: <b>{level}</b>\n📖 واژهٔ روز: <b>{daily}</b> {time}\n🔘 ربات: <b>{enabled}</b>", "⚙️ <b>Group settings</b>\n\n🌐 Message language: <b>{ui}</b>\n💬 Explanation language: <b>{expl}</b>\n📶 Level: <b>{level}</b>\n📖 Word of the day: <b>{daily}</b> {time}\n🔘 Bot: <b>{enabled}</b>", "⚙️ <b>Gruppeneinstellungen</b>\n\n🌐 Nachrichtensprache: <b>{ui}</b>\n💬 Erklärungssprache: <b>{expl}</b>\n📶 Niveau: <b>{level}</b>\n📖 Wort des Tages: <b>{daily}</b> {time}\n🔘 Bot: <b>{enabled}</b>")
S("b_g_daily", "📖 واژهٔ روز", "📖 Word of the day", "📖 Wort des Tages")
S("b_g_time", "🕒 ساعت", "🕒 Time", "🕒 Uhrzeit")
S("b_g_enabled", "🔘 روشن/خاموش", "🔘 Enable/disable", "🔘 An/Aus")
S("g_time_ask", "ساعت ارسال واژهٔ روز را بفرست (HH:MM، به وقت تهران).", "Send the time for the daily word (HH:MM, Tehran time).", "Schick die Uhrzeit für das Tageswort (HH:MM, Teheraner Zeit).")
S("g_quiz_head", "🧠 <b>تمرین گروهی</b> — اولین جواب درست امتیاز می‌گیرد! (هر نفر یک بار)", "🧠 <b>Group quiz</b> — first correct answer scores! (one try each)", "🧠 <b>Gruppenquiz</b> — die erste richtige Antwort punktet! (ein Versuch pro Person)")
S("g_quiz_win", "🏆 <b>{name}</b> اول جواب درست داد! +{pts} امتیاز\n\n✔️ {ans}\n{expl}", "🏆 <b>{name}</b> answered first! +{pts} points\n\n✔️ {ans}\n{expl}", "🏆 <b>{name}</b> war zuerst richtig! +{pts} Punkte\n\n✔️ {ans}\n{expl}")
S("g_quiz_timeout", "⌛ وقت تمام شد؛ کسی جواب درست نداد.\n✔️ جواب: {ans}\n{expl}", "⌛ Time's up; nobody got it.\n✔️ Answer: {ans}\n{expl}", "⌛ Zeit abgelaufen; niemand hatte es.\n✔️ Antwort: {ans}\n{expl}")
S("g_quiz_wrong", "❌ نادرست؛ فقط یک بار می‌توانی جواب بدهی.", "❌ Wrong; you only get one try.", "❌ Falsch; du hast nur einen Versuch.")
S("g_quiz_done", "✅ تو قبلاً جواب دادی.", "✅ You've already answered.", "✅ Du hast schon geantwortet.")
S("g_quiz_closed", "این تمرین بسته شده است.", "This quiz is closed.", "Dieses Quiz ist geschlossen.")
S("g_quiz_cool", "⏳ چند ثانیه صبر کن تا تمرین بعدی.", "⏳ Wait a few seconds for the next quiz.", "⏳ Warte ein paar Sekunden bis zum nächsten Quiz.")
S("g_top", "🏆 <b>جدول امتیازات گروه</b>\n\n{lines}", "🏆 <b>Group leaderboard</b>\n\n{lines}", "🏆 <b>Gruppen-Rangliste</b>\n\n{lines}")
S("g_top_empty", "هنوز امتیازی ثبت نشده. /quiz را امتحان کنید!", "No scores yet. Try /quiz!", "Noch keine Punkte. Probiert /quiz!")
S("g_top_line", "{rank}. {name} — {pts} امتیاز ({wins} برد)", "{rank}. {name} — {pts} pts ({wins} wins)", "{rank}. {name} — {pts} Pkt. ({wins} Siege)")
S("g_word_head", "📖 <b>واژهٔ روز</b>", "📖 <b>Word of the day</b>", "📖 <b>Wort des Tages</b>")
S("g_ask_private", "💬 برای ادامهٔ پرسش و پاسخ شخصی، چت خصوصی را باز کن (پیشرفت تو آنجا جداگانه ثبت می‌شود).", "💬 To continue personal Q&A, open the private chat (your progress is stored separately there).", "💬 Für persönliche Fragen öffne den Privatchat (dein Fortschritt wird dort getrennt gespeichert).")
S("g_dm_start", "👋 از گروه «{title}» آمدی. اینجا پیشرفتت شخصی و جداست. چه کنیم؟", "👋 You came from the group “{title}”. Here your progress is personal and separate. What shall we do?", "👋 Du kommst aus der Gruppe „{title}“. Hier ist dein Fortschritt persönlich und getrennt. Was machen wir?")

# ---------- admin ----------
S("a_title", "🛠 <b>پنل مدیر</b>", "🛠 <b>Admin panel</b>", "🛠 <b>Admin-Panel</b>")
S("a_b_stats", "📊 آمار", "📊 Stats", "📊 Statistik")
S("a_b_users", "👥 کاربران", "👥 Users", "👥 Nutzer")
S("a_b_groups", "👪 گروه‌ها", "👪 Groups", "👪 Gruppen")
S("a_b_channels", "📣 کانال‌ها", "📣 Channels", "📣 Kanäle")
S("a_b_bc", "📢 پیام همگانی", "📢 Broadcast", "📢 Rundnachricht")
S("a_b_content", "✏️ محتوا", "✏️ Content", "✏️ Inhalte")
S("a_b_settings", "⚙️ تنظیمات", "⚙️ Settings", "⚙️ Einstellungen")
S("a_b_export", "📦 خروجی", "📦 Export", "📦 Export")
S("a_back", "⬅️ پنل", "⬅️ Panel", "⬅️ Panel")
S("a_stats", "📊 <b>آمار</b>\n\n👥 کاربران: {users} (۲۴ ساعت اخیر: +{new24})\n🟢 فعال امروز: {active_today} • ۷ روز: {active7}\n🚫 مسدود: {banned}\n👪 گروه‌ها: {groups} (ادمین در {groups_admin})\n📣 کانال‌ها: {channels}\n📚 کارت‌ها: {cards}\n🧠 پاسخ‌ها: {answers} (درست: {correct})\n❗ اشتباهات ثبت‌شده: {mistakes}\n🏆 کوییز گروهی: {gquizzes}\n⏰ کاربران با یادآور: {reminders}\n🤖 پاسخ هوش مصنوعی امروز: {llm_today}\n\n🤖 هوش مصنوعی: {llm}\n🎧 TTS: {tts}", "📊 <b>Stats</b>\n\n👥 Users: {users} (last 24h: +{new24})\n🟢 Active today: {active_today} • 7 days: {active7}\n🚫 Banned: {banned}\n👪 Groups: {groups} (admin in {groups_admin})\n📣 Channels: {channels}\n📚 Cards: {cards}\n🧠 Answers: {answers} (correct: {correct})\n❗ Logged mistakes: {mistakes}\n🏆 Group quizzes: {gquizzes}\n⏰ Users with reminder: {reminders}\n🤖 AI answers today: {llm_today}\n\n🤖 AI: {llm}\n🎧 TTS: {tts}", "📊 <b>Statistik</b>\n\n👥 Nutzer: {users} (letzte 24 h: +{new24})\n🟢 Heute aktiv: {active_today} • 7 Tage: {active7}\n🚫 Gesperrt: {banned}\n👪 Gruppen: {groups} (Admin in {groups_admin})\n📣 Kanäle: {channels}\n📚 Karten: {cards}\n🧠 Antworten: {answers} (richtig: {correct})\n❗ Protokollierte Fehler: {mistakes}\n🏆 Gruppenquizze: {gquizzes}\n⏰ Nutzer mit Erinnerung: {reminders}\n🤖 KI-Antworten heute: {llm_today}\n\n🤖 KI: {llm}\n🎧 TTS: {tts}")
S("a_users", "👥 <b>کاربران</b> — صفحه {page}/{pages} (کل: {total})", "👥 <b>Users</b> — page {page}/{pages} (total: {total})", "👥 <b>Nutzer</b> — Seite {page}/{pages} (gesamt: {total})")
S("a_user_card", "👤 <b>{name}</b> {uname}\nشناسه: <code>{id}</code>\nسطح: {level} • امتیاز: {xp} • رگه: {streak}\nپاسخ‌ها: {ok}/{tot} • کارت‌ها: {cards}\nزبان: {ui}/{expl}\nوضعیت: {status}", "👤 <b>{name}</b> {uname}\nID: <code>{id}</code>\nLevel: {level} • XP: {xp} • streak: {streak}\nAnswers: {ok}/{tot} • cards: {cards}\nLang: {ui}/{expl}\nStatus: {status}", "👤 <b>{name}</b> {uname}\nID: <code>{id}</code>\nNiveau: {level} • XP: {xp} • Serie: {streak}\nAntworten: {ok}/{tot} • Karten: {cards}\nSprache: {ui}/{expl}\nStatus: {status}")
S("a_search", "🔎 جستجو", "🔎 Search", "🔎 Suchen")
S("a_search_ask", "نام، @یوزرنیم یا شناسهٔ عددی را بفرست:", "Send a name, @username or numeric id:", "Schick Name, @Benutzername oder numerische ID:")
S("a_ban", "🚫 مسدود", "🚫 Ban", "🚫 Sperren")
S("a_unban", "✅ رفع مسدودی", "✅ Unban", "✅ Entsperren")
S("a_make_admin", "👑 ادمین کن", "👑 Make admin", "👑 Zum Admin machen")
S("a_rm_admin", "➖ حذف ادمین", "➖ Remove admin", "➖ Admin entziehen")
S("a_reset", "♻️ ریست پیشرفت", "♻️ Reset progress", "♻️ Fortschritt zurücksetzen")
S("a_not_found", "پیدا نشد.", "Not found.", "Nicht gefunden.")
S("a_done", "✅ انجام شد.", "✅ Done.", "✅ Erledigt.")
S("a_owner_only", "🔒 فقط مالک.", "🔒 Owner only.", "🔒 Nur Eigentümer.")
S("a_groups", "👪 <b>گروه‌ها</b> ({n})", "👪 <b>Groups</b> ({n})", "👪 <b>Gruppen</b> ({n})")
S("a_group_card", "👪 <b>{title}</b>\nشناسه: <code>{id}</code>\nزبان: {ui}/{expl} • سطح: {level}\nواژهٔ روز: {daily} {time}\nادمین ربات: {admin} • فعال: {enabled}", "👪 <b>{title}</b>\nID: <code>{id}</code>\nLang: {ui}/{expl} • level: {level}\nDaily word: {daily} {time}\nBot admin: {admin} • enabled: {enabled}", "👪 <b>{title}</b>\nID: <code>{id}</code>\nSprache: {ui}/{expl} • Niveau: {level}\nTageswort: {daily} {time}\nBot-Admin: {admin} • aktiv: {enabled}")
S("a_leave", "🚪 خروج از گروه", "🚪 Leave group", "🚪 Gruppe verlassen")
S("a_bc_target", "📢 <b>پیام همگانی</b>\nگیرنده‌ها را انتخاب کن:", "📢 <b>Broadcast</b>\nChoose recipients:", "📢 <b>Rundnachricht</b>\nEmpfänger wählen:")
S("a_bc_users", "👥 همهٔ کاربران ({n})", "👥 All users ({n})", "👥 Alle Nutzer ({n})")
S("a_bc_groups", "👪 همهٔ گروه‌ها ({n})", "👪 All groups ({n})", "👪 Alle Gruppen ({n})")
S("a_bc_text", "متن پیام را بفرست (HTML ساده مجاز است). برای لغو /cancel.", "Send the message text (basic HTML allowed). /cancel to abort.", "Schick den Nachrichtentext (einfaches HTML erlaubt). /cancel zum Abbrechen.")
S("a_bc_confirm", "پیش‌نمایش:\n\n{text}\n\nارسال به {n} گیرنده (حدود {sec} ثانیه، با محدودیت سرعت)؟", "Preview:\n\n{text}\n\nSend to {n} recipients (about {sec}s, throttled)?", "Vorschau:\n\n{text}\n\nAn {n} Empfänger senden (ca. {sec} s, gedrosselt)?")
S("a_bc_started", "🚀 ارسال شروع شد.", "🚀 Broadcast started.", "🚀 Versand gestartet.")
S("a_bc_report", "📢 ارسال تمام شد: ✅ {sent} • ❌ {failed}", "📢 Broadcast finished: ✅ {sent} • ❌ {failed}", "📢 Versand beendet: ✅ {sent} • ❌ {failed}")
S("a_content", "✏️ <b>مدیریت محتوا</b>\nلغت، درس و تمرین دلخواه اضافه کن.\nلغت‌ها: {nw} • درس‌ها: {nl} • تمرین‌ها: {ne}", "✏️ <b>Content editor</b>\nAdd custom words, lessons and exercises.\nWords: {nw} • lessons: {nl} • exercises: {ne}", "✏️ <b>Inhalts-Editor</b>\nEigene Wörter, Lektionen und Übungen hinzufügen.\nWörter: {nw} • Lektionen: {nl} • Übungen: {ne}")
S("a_add_word", "➕ لغت", "➕ Word", "➕ Wort")
S("a_add_lesson", "➕ درس", "➕ Lesson", "➕ Lektion")
S("a_add_ex", "➕ تمرین", "➕ Exercise", "➕ Übung")
S("a_list_custom", "📋 فهرست", "📋 List", "📋 Liste")
S("a_word_fmt", "لغت را در یک خط بفرست:\n<code>汉字 | pinyin | معنی فارسی | English | Deutsch | سطح(1-3)</code>\nمثال:\n<code>咖啡厅 | kāfēi tīng | کافه | cafe | Café | 2</code>", "Send the word on one line:\n<code>汉字 | pinyin | Persian | English | German | level(1-3)</code>\nExample:\n<code>咖啡厅 | kāfēi tīng | کافه | cafe | Café | 2</code>", "Schick das Wort in einer Zeile:\n<code>汉字 | pinyin | Persisch | Englisch | Deutsch | Niveau(1-3)</code>\nBeispiel:\n<code>咖啡厅 | kāfēi tīng | کافه | cafe | Café | 2</code>")
S("a_lesson_fmt", "درس را بفرست: خط اول عنوان، بقیه متن. به «درس امروز» اضافه می‌شود.", "Send the lesson: first line is the title, the rest is the text. It is added to “Today's lesson”.", "Schick die Lektion: erste Zeile Titel, der Rest Text. Sie wird zur „Heutigen Lektion“ hinzugefügt.")
S("a_ex_fmt", "تمرین را بفرست (یک خط):\n<code>سؤال | گزینهٔ درست | غلط۱ | غلط۲ | غلط۳ | توضیح (اختیاری)</code>", "Send the exercise (one line):\n<code>question | correct | wrong1 | wrong2 | wrong3 | explanation (optional)</code>", "Schick die Übung (eine Zeile):\n<code>Frage | richtig | falsch1 | falsch2 | falsch3 | Erklärung (optional)</code>")
S("a_bad_fmt", "⚠️ قالب نادرست است؛ دوباره بفرست.", "⚠️ Wrong format; send again.", "⚠️ Falsches Format; bitte erneut senden.")
S("a_added", "✅ اضافه شد (شناسه {id}).", "✅ Added (id {id}).", "✅ Hinzugefügt (ID {id}).")
S("a_custom_none", "هنوز موردی اضافه نشده.", "Nothing added yet.", "Noch nichts hinzugefügt.")
S("a_toggle", "🔀 روشن/خاموش", "🔀 Toggle", "🔀 An/Aus")
S("a_delete", "🗑 حذف", "🗑 Delete", "🗑 Löschen")
S("a_set", "⚙️ <b>تنظیمات مدیر</b>\n\n🤖 هوش مصنوعی: <b>{llm}</b>\n🌐 آدرس پایه: <code>{base}</code>\n🧠 مدل: <code>{model}</code>\n🎤 مدل گفتار‌به‌متن: <code>{stt}</code>\n📏 سقف روزانهٔ هر کاربر: <b>{limit}</b>\n🔑 کلید API: {key}\n\n<i>کلید فقط از متغیر محیطی CHINESE_LLM_API_KEY خوانده می‌شود و هرگز ذخیره/نمایش داده نمی‌شود.</i>", "⚙️ <b>Admin settings</b>\n\n🤖 AI: <b>{llm}</b>\n🌐 Base URL: <code>{base}</code>\n🧠 Model: <code>{model}</code>\n🎤 Speech-to-text model: <code>{stt}</code>\n📏 Daily limit per user: <b>{limit}</b>\n🔑 API key: {key}\n\n<i>The key is read only from the CHINESE_LLM_API_KEY environment variable and is never stored or shown.</i>", "⚙️ <b>Admin-Einstellungen</b>\n\n🤖 KI: <b>{llm}</b>\n🌐 Basis-URL: <code>{base}</code>\n🧠 Modell: <code>{model}</code>\n🎤 Speech-to-Text-Modell: <code>{stt}</code>\n📏 Tageslimit pro Nutzer: <b>{limit}</b>\n🔑 API-Schlüssel: {key}\n\n<i>Der Schlüssel wird nur aus der Umgebungsvariable CHINESE_LLM_API_KEY gelesen und nie gespeichert oder angezeigt.</i>")
S("a_key_set", "✅ تنظیم شده", "✅ set", "✅ gesetzt")
S("a_key_unset", "❌ تنظیم نشده — برای فعال‌سازی: export CHINESE_LLM_API_KEY=… و ری‌استارت", "❌ not set — to enable: export CHINESE_LLM_API_KEY=… and restart", "❌ nicht gesetzt — zum Aktivieren: export CHINESE_LLM_API_KEY=… und neu starten")
S("a_s_toggle", "🤖 روشن/خاموش", "🤖 AI on/off", "🤖 KI an/aus")
S("a_s_base", "🌐 آدرس پایه", "🌐 Base URL", "🌐 Basis-URL")
S("a_s_model", "🧠 مدل", "🧠 Model", "🧠 Modell")
S("a_s_stt", "🎤 مدل STT", "🎤 STT model", "🎤 STT-Modell")
S("a_s_limit", "📏 سقف روزانه", "📏 Daily limit", "📏 Tageslimit")
S("a_s_ask", "مقدار جدید را بفرست:", "Send the new value:", "Schick den neuen Wert:")
S("a_export", "📦 <b>خروجی</b>\nیک فایل zip با کاربران، پیشرفت، گروه‌ها و محتوای سفارشی (JSON + CSV) می‌سازم. بدون توکن/کلید.", "📦 <b>Export</b>\nI'll build a zip with users, progress, groups and custom content (JSON + CSV). No tokens/keys.", "📦 <b>Export</b>\nIch erstelle ein ZIP mit Nutzern, Fortschritt, Gruppen und eigenen Inhalten (JSON + CSV). Keine Tokens/Schlüssel.")
S("a_export_go", "📦 ساخت و ارسال", "📦 Build & send", "📦 Erstellen & senden")
S("a_on", "روشن ✅", "On ✅", "An ✅")
S("a_off", "خاموش ⛔", "Off ⛔", "Aus ⛔")

# ---------- channels ----------
S("c_title", "📣 <b>کانال‌ها</b>\nربات را در کانال «ادمین» کن؛ بعد از آن کانال اینجا ظاهر می‌شود.\nثبت‌شده: {n}", "📣 <b>Channels</b>\nMake the bot an admin of your channel; it will then appear here.\nRegistered: {n}", "📣 <b>Kanäle</b>\nMache den Bot zum Admin deines Kanals; er erscheint dann hier.\nRegistriert: {n}")
S("c_pending", "🆕 شناسایی‌شده: {title}", "🆕 Detected: {title}", "🆕 Erkannt: {title}")
S("c_add", "➕ ثبت با شناسه/یوزرنیم", "➕ Register by id/username", "➕ Per ID/Benutzername registrieren")
S("c_add_ask", "یوزرنیم کانال (مثلاً @mychannel) یا شناسهٔ عددی (‎-100…) را بفرست. ربات باید در کانال ادمین با حق ارسال پیام باشد.", "Send the channel username (e.g. @mychannel) or numeric id (-100…). The bot must be a channel admin allowed to post.", "Schick den Kanal-Benutzernamen (z. B. @mychannel) oder die numerische ID (-100…). Der Bot muss Kanal-Admin mit Senderecht sein.")
S("c_added", "✅ کانال ثبت شد: {title}", "✅ Channel registered: {title}", "✅ Kanal registriert: {title}")
S("c_fail", "⚠️ نشد: {err}\nمطمئن شو ربات در کانال ادمین است و حق «ارسال پیام» دارد.", "⚠️ Failed: {err}\nMake sure the bot is a channel admin with “post messages” right.", "⚠️ Fehlgeschlagen: {err}\nStelle sicher, dass der Bot Kanal-Admin mit dem Recht „Nachrichten posten“ ist.")
S("c_card", "📣 <b>{title}</b> {uname}\nوضعیت: {enabled}\n🕒 ساعت‌های ارسال ({tz}): {times}\n🧩 انواع محتوا: {types}\n🌐 زبان: {lang}\n🔘 دکمهٔ «تمرین در ربات»: {btn}\n📮 ارسال‌شده: {counter}", "📣 <b>{title}</b> {uname}\nStatus: {enabled}\n🕒 Post times ({tz}): {times}\n🧩 Content types: {types}\n🌐 Language: {lang}\n🔘 “Practice in the bot” button: {btn}\n📮 Posted: {counter}", "📣 <b>{title}</b> {uname}\nStatus: {enabled}\n🕒 Sendezeiten ({tz}): {times}\n🧩 Inhaltstypen: {types}\n🌐 Sprache: {lang}\n🔘 Schaltfläche „Im Bot üben“: {btn}\n📮 Gepostet: {counter}")
S("c_b_toggle", "🔘 روشن/خاموش", "🔘 On/off", "🔘 An/Aus")
S("c_b_times", "🕒 ساعت‌ها", "🕒 Times", "🕒 Zeiten")
S("c_b_types", "🧩 انواع محتوا", "🧩 Content types", "🧩 Inhaltstypen")
S("c_b_lang", "🌐 زبان پست‌ها", "🌐 Post language", "🌐 Post-Sprache")
S("c_b_btn", "🔘 دکمهٔ ربات", "🔘 Bot button", "🔘 Bot-Schaltfläche")
S("c_b_now", "📮 ارسال همین حالا", "📮 Post now", "📮 Jetzt posten")
S("c_b_pin", "📌 ارسال و سنجاق پست معرفی", "📌 Post & pin intro", "📌 Intro posten & anpinnen")
S("c_b_del", "🗑 حذف از لیست", "🗑 Remove", "🗑 Entfernen")
S("c_times_ask", "ساعت‌های ارسال را با فاصله یا کاما بفرست، مثلاً: <code>09:00 13:00 18:00 21:00</code>", "Send post times separated by spaces or commas, e.g. <code>09:00 13:00 18:00 21:00</code>", "Schick Sendezeiten, getrennt durch Leerzeichen oder Komma, z. B. <code>09:00 13:00 18:00 21:00</code>")
S("c_posted", "✅ ارسال شد.", "✅ Posted.", "✅ Gepostet.")
S("c_pin_note", "برای سنجاق کردن، ربات باید حق «Pin messages» داشته باشد.", "To pin, the bot needs the “Pin messages” right.", "Zum Anpinnen braucht der Bot das Recht „Nachrichten anheften“.")
S("c_detected", "📣 ربات به‌عنوان ادمین به کانال «{title}» اضافه شد. برای ثبت و برنامه‌ریزی ارسال خودکار: /admin ← کانال‌ها.", "📣 The bot was added as admin to channel “{title}”. To register it and schedule posts: /admin → Channels.", "📣 Der Bot wurde als Admin zum Kanal „{title}“ hinzugefügt. Zum Registrieren und Planen: /admin → Kanäle.")
S("c_type_word", "📖 واژهٔ روز", "📖 Word of the day", "📖 Wort des Tages")
S("c_type_char", "✍️ نویسه و ترتیب خط", "✍️ Character & strokes", "✍️ Zeichen & Strichfolge")
S("c_type_tone", "🎵 نکتهٔ لحن", "🎵 Tone tip", "🎵 Tontipp")
S("c_type_quiz", "🧠 آزمونک HSK", "🧠 HSK mini-quiz", "🧠 HSK-Minitest")
S("c_type_grammar", "📘 نکتهٔ دستوری", "📘 Grammar tip", "📘 Grammatiktipp")
S("c_type_idiom", "📜 ضرب‌المثل (成语)", "📜 Idiom (成语)", "📜 Redewendung (成语)")
S("c_type_culture", "🏮 فرهنگ", "🏮 Culture", "🏮 Kultur")
S("c_post_word", "📖 <b>واژهٔ روز</b> #HSK{lv}\n\n{hz}\n<b>{py}</b>\n\n🇮🇷 {fa}\n🇬🇧 {en}\n🇩🇪 {de}{ex}\n\n#چینی #آموزش_چینی #HSK{lv} #LearnChinese", "📖 <b>Word of the day</b> #HSK{lv}\n\n{hz}\n<b>{py}</b>\n\n🇮🇷 {fa}\n🇬🇧 {en}\n🇩🇪 {de}{ex}\n\n#LearnChinese #HSK{lv} #Mandarin", "📖 <b>Wort des Tages</b> #HSK{lv}\n\n{hz}\n<b>{py}</b>\n\n🇮🇷 {fa}\n🇬🇧 {en}\n🇩🇪 {de}{ex}\n\n#ChinesischLernen #HSK{lv} #Mandarin")
S("c_post_tone", "🎵 <b>نکتهٔ تلفظ</b>\n\n{t}\n\n#لحن #تلفظ_چینی #پینیین", "🎵 <b>Pronunciation tip</b>\n\n{t}\n\n#Tones #Pinyin #LearnChinese", "🎵 <b>Aussprachetipp</b>\n\n{t}\n\n#Töne #Pinyin #ChinesischLernen")
S("c_post_grammar", "📘 <b>نکتهٔ دستوری: {title}</b>\n<code>{pattern}</code>\n\n{body}\n\n🈶 {zh}\n<i>{py}</i>\n{tr}\n\n#دستور_چینی #HSK", "📘 <b>Grammar tip: {title}</b>\n<code>{pattern}</code>\n\n{body}\n\n🈶 {zh}\n<i>{py}</i>\n{tr}\n\n#ChineseGrammar #HSK", "📘 <b>Grammatiktipp: {title}</b>\n<code>{pattern}</code>\n\n{body}\n\n🈶 {zh}\n<i>{py}</i>\n{tr}\n\n#ChinesischGrammatik #HSK")
S("c_post_idiom", "📜 <b>ضرب‌المثل چینی (成语)</b>\n\n{zh}\n<i>{py}</i>\n\n{mean}\n🔤 {lit}\n\n#成语 #ضرب_المثل_چینی", "📜 <b>Chinese idiom (成语)</b>\n\n{zh}\n<i>{py}</i>\n\n{mean}\n🔤 {lit}\n\n#成语 #Chengyu", "📜 <b>Chinesische Redewendung (成语)</b>\n\n{zh}\n<i>{py}</i>\n\n{mean}\n🔤 {lit}\n\n#成语 #Chengyu")
S("c_post_culture", "🏮 <b>{title}</b>\n\n{body}\n\n#فرهنگ_چین", "🏮 <b>{title}</b>\n\n{body}\n\n#ChineseCulture", "🏮 <b>{title}</b>\n\n{body}\n\n#ChinesischeKultur")
S("c_post_char", "✍️ <b>نویسهٔ روز: {ch}</b> ({py})\n{mean}\n🖌 {n} خط • ریشه: {rad}\n\n#ترتیب_خط #نویسه_چینی", "✍️ <b>Character of the day: {ch}</b> ({py})\n{mean}\n🖌 {n} strokes • radical: {rad}\n\n#StrokeOrder #Hanzi", "✍️ <b>Zeichen des Tages: {ch}</b> ({py})\n{mean}\n🖌 {n} Striche • Radikal: {rad}\n\n#Strichfolge #Hanzi")
S("c_quiz_q", "🧠 آزمونک HSK {lv}: «{hz}» یعنی چه؟", "🧠 HSK {lv} mini-quiz: what does “{hz}” mean?", "🧠 HSK-{lv}-Minitest: Was bedeutet „{hz}“?")
S("c_quiz_expl", "{hz} ({py}) = {mean}", "{hz} ({py}) = {mean}", "{hz} ({py}) = {mean}")
S("c_intro", "🇨🇳 <b>{name}</b>\n\nبه کانال آموزش چینی (ماندارین) برای فارسی‌زبان‌ها خوش آمدی!\n\n📖 هر روز: واژهٔ HSK با تلفظ و معنی فارسی/انگلیسی/آلمانی\n🎵 نکتهٔ لحن و تلفظ\n✍️ نویسه و ترتیب نوشتن\n🧠 آزمونک‌های HSK\n📘 نکتهٔ دستور زبان\n📜 ضرب‌المثل‌های چینی (成语) و فرهنگ\n\n🤖 تمرین شخصی، مرور هوشمند و پرسش و پاسخ: @{bot}\n\n📌 این پست را سنجاق کن و کانال را به دوستانت معرفی کن 🙏", "🇨🇳 <b>{name}</b>\n\nWelcome to the Mandarin Chinese learning channel!\n\n📖 Daily: HSK word with pronunciation and Persian/English/German meaning\n🎵 Tone & pronunciation tips\n✍️ Characters & stroke order\n🧠 HSK mini-quizzes\n📘 Grammar tips\n📜 Chinese idioms (成语) & culture\n\n🤖 Personal practice, smart review and Q&A: @{bot}\n\n📌 Pin this post and share the channel with friends 🙏", "🇨🇳 <b>{name}</b>\n\nWillkommen im Mandarin-Lernkanal!\n\n📖 Täglich: HSK-Wort mit Aussprache und Bedeutung auf Persisch/Englisch/Deutsch\n🎵 Ton- & Ausspracheregeln\n✍️ Zeichen & Strichfolge\n🧠 HSK-Minitests\n📘 Grammatiktipps\n📜 Chinesische Redewendungen (成语) & Kultur\n\n🤖 Persönliches Üben, smarte Wiederholung und Fragen: @{bot}\n\n📌 Pinne diesen Post und teile den Kanal mit Freunden 🙏")
S("c_btn_label", "📝 تمرین در ربات", "📝 Practice in the bot", "📝 Im Bot üben")

# ---------- group extras ----------
S("g_btn_private", "💬 باز کردن گفتگوی خصوصی", "💬 Open private chat", "💬 Privatchat öffnen")
S("g_btn_settings", "⚙️ تنظیمات گروه (ادمین‌ها)", "⚙️ Group settings (admins)", "⚙️ Gruppeneinstellungen (Admins)")
S("g_btn_next", "➡️ سؤال بعدی", "➡️ Next question", "➡️ Nächste Frage")
S("g_btn_top", "🏆 رتبه‌ها", "🏆 Leaderboard", "🏆 Rangliste")
S("g_pick", "انتخاب کن:", "Choose:", "Wähle:")
S("g_quiz_open", "⏳ یک آزمون باز است؛ همان را جواب بدهید.", "⏳ A quiz is already open; answer that one.", "⏳ Es läuft schon ein Quiz; beantwortet das.")
S("g_b_ui", "🌐 زبان", "🌐 Language", "🌐 Sprache")
S("g_b_expl", "💬 توضیحات", "💬 Explanations", "💬 Erklärungen")
S("g_b_level", "📶 سطح", "📶 Level", "📶 Niveau")
S("g_b_daily", "📖 واژهٔ روز", "📖 Word of the day", "📖 Wort des Tages")
S("g_b_time", "🕒 ساعت", "🕒 Time", "🕒 Uhrzeit")
S("g_b_pin", "📌 سنجاق", "📌 Pin", "📌 Anpinnen")
S("g_b_enabled", "🔘 فعال", "🔘 Enabled", "🔘 Aktiv")
S("g_time_set", "✅ واژهٔ روز هر روز ساعت {t} (وقت تهران) فرستاده می‌شود.", "✅ The word of the day will be posted daily at {t} (Tehran time).", "✅ Das Wort des Tages kommt täglich um {t} Uhr (Teheraner Zeit).")
S("g_need_arg", "چیزی بعد از دستور بنویس. مثال: /dict 学校", "Write something after the command. Example: /dict 学校", "Schreib etwas hinter den Befehl. Beispiel: /dict 学校")
S("g_hi", "سلام! 👋 دستورها: /quiz /word /dict /ask /top. برای تمرین شخصی، گفتگوی خصوصی را باز کن.", "Hi! 👋 Commands: /quiz /word /dict /ask /top. For personal practice open the private chat.", "Hallo! 👋 Befehle: /quiz /word /dict /ask /top. Für persönliches Üben öffne den Privatchat.")
S("g_unknown", "این دستور را نمی‌شناسم. /start را بزن برای راهنما.", "I don't know that command. Send /start for help.", "Diesen Befehl kenne ich nicht. Sende /start für Hilfe.")

# ---------- admin extras ----------
S("a_menu_hint", "یکی را انتخاب کن:", "Choose a section:", "Wähle einen Bereich:")
S("a_page", "{page}/{pages}", "{page}/{pages}", "{page}/{pages}")
S("a_ask_id", "شناسه را بفرست:", "Send the id:", "Sende die ID:")
S("a_yes_go", "✅ ارسال", "✅ Send", "✅ Senden")
S("a_cancel", "❌ لغو", "❌ Cancel", "❌ Abbrechen")
S("a_cancelled", "لغو شد.", "Cancelled.", "Abgebrochen.")
S("a_export_none", "ارسال فایل ناموفق بود.", "Could not send the file.", "Datei konnte nicht gesendet werden.")
S("a_val_bad", "مقدار نامعتبر.", "Invalid value.", "Ungültiger Wert.")
S("a_group_none", "گروهی ثبت نشده.", "No groups yet.", "Noch keine Gruppen.")
S("c_none", "کانالی ثبت نشده است.", "No channels registered yet.", "Noch keine Kanäle registriert.")
S("c_types_head", "🧩 نوع محتوای کانال را انتخاب کن (چندتایی):", "🧩 Choose content types (multiple):", "🧩 Wähle Inhaltstypen (mehrere):")
S("c_times_set", "✅ ساعت‌ها: {times}", "✅ Times: {times}", "✅ Zeiten: {times}")
S("c_pinned", "📌 پست معرفی ارسال و سنجاق شد.", "📌 Intro post sent and pinned.", "📌 Intro-Post gesendet und angepinnt.")
S("c_pin_fail", "پست ارسال شد ولی سنجاق نشد (دسترسی «سنجاق پیام» را بده).", "Posted, but pinning failed (grant “Pin messages”).", "Gepostet, aber Anpinnen fehlgeschlagen (Recht „Nachrichten anpinnen“ geben).")
S("c_post_fail", "ارسال ناموفق: {err}", "Post failed: {err}", "Posten fehlgeschlagen: {err}")
S("c_removed", "کانال از زمان‌بندی حذف شد.", "Channel removed from the schedule.", "Kanal aus dem Zeitplan entfernt.")
S("c_bot_label", "ربات: @{bot}", "Bot: @{bot}", "Bot: @{bot}")
S("bc_msg_prefix", "", "", "")
S("a_cmd_hint", "از /admin استفاده کن.", "Use /admin.", "Nutze /admin.")

S("top_private", "🏆 رتبه‌بندی گروهی فقط در گروه‌ها نمایش داده می‌شود: من را به گروهتان اضافه کنید و /top را بزنید. پیشرفت شخصی‌ات: /progress", "🏆 Leaderboards are group-only: add me to a group and send /top. Your personal progress: /progress", "🏆 Ranglisten gibt es nur in Gruppen: füge mich zu einer Gruppe hinzu und sende /top. Dein persönlicher Fortschritt: /progress")
S("banned_msg", "⛔ دسترسی شما محدود شده است.", "⛔ Your access has been restricted.", "⛔ Dein Zugang wurde eingeschränkt.")
S("rate_msg", "⏳ کمی آهسته‌تر لطفاً.", "⏳ Please slow down a little.", "⏳ Bitte etwas langsamer.")
S("stroke_usage", "یک نویسهٔ چینی بنویس. مثال: /stroke 学", "Send a Chinese character. Example: /stroke 学", "Sende ein chinesisches Zeichen. Beispiel: /stroke 学")
S("cancelled", "✅ لغو شد.", "✅ Cancelled.", "✅ Abgebrochen.")
S("not_admin", "🔒 این بخش فقط برای ادمین‌هاست.", "🔒 This section is for admins only.", "🔒 Dieser Bereich ist nur für Admins.")

# ---------- group teacher mode ----------
S("g_b_teacher", "🎓 حالت معلم", "🎓 Teacher mode", "🎓 Lehrer-Modus")
S("g_tm_always", "همیشه", "always", "immer")
S("g_tm_mention", "فقط با منشن/ریپلای", "only when mentioned", "nur bei Erwähnung")
S("g_tm_off", "خاموش", "off", "aus")
S("g_teacher_line", "🎓 حالت معلم: <b>{mode}</b>", "🎓 Teacher mode: <b>{mode}</b>", "🎓 Lehrer-Modus: <b>{mode}</b>")
S("g_teacher_intro", "🎓 <b>حالت معلم:</b> به پیام‌های مربوط به چینی (جمله‌های چینی، سؤال دربارهٔ چینی) جواب می‌دهم، جمله‌ها را مهربانانه اصلاح می‌کنم و تمرین کوچک می‌دهم. برای جلوگیری از مزاحمت، بین پاسخ‌ها فاصله می‌گذارم. ادمین‌ها در /settings می‌توانند «همیشه / فقط با منشن / خاموش» را انتخاب کنند.",
  "🎓 <b>Teacher mode:</b> I reply to messages about Chinese (Chinese sentences, questions about Chinese), gently correct sentences and give mini-exercises. I leave gaps between replies so I never spam. Admins can choose “always / only when mentioned / off” in /settings.",
  "🎓 <b>Lehrer-Modus:</b> Ich antworte auf Nachrichten über Chinesisch (chinesische Sätze, Fragen zu Chinesisch), korrigiere Sätze freundlich und gebe Mini-Übungen. Zwischen Antworten lasse ich Pausen, damit ich nicht nerve. Admins wählen in /settings „immer / nur bei Erwähnung / aus“.")
S("t_off_hint", "حالت معلم در این گروه خاموش است؛ از دستورهای /dict و /ask استفاده کنید.", "Teacher mode is off in this group; use the /dict and /ask commands.", "Der Lehrer-Modus ist in dieser Gruppe aus; nutzt die Befehle /dict und /ask.")
S("t_greet", "سلام {name}! 😊 من معلم چینی‌ام. یک جملهٔ چینی بنویس تا با هم بررسی کنیم، یا سؤالت را بپرس. برای تمرین کوچک دکمهٔ زیر را بزن.", "Hello {name}! 😊 I'm the Chinese teacher. Write a Chinese sentence and we'll look at it together, or just ask a question. Tap below for a mini-exercise.", "Hallo {name}! 😊 Ich bin der Chinesisch-Lehrer. Schreib einen chinesischen Satz, dann schauen wir ihn uns an, oder stell einfach eine Frage. Unten gibt es eine Mini-Übung.")
S("t_thanks", "خواهش می‌کنم {name}! 🌟 همین که تمرین می‌کنی عالی است. یک تمرین کوچک دیگر؟", "You're welcome, {name}! 🌟 Practising regularly is what counts. Another mini-exercise?", "Gern geschehen, {name}! 🌟 Regelmäßiges Üben zählt. Noch eine Mini-Übung?")
S("t_praise_1", "👏 آفرین {name}! جملهٔ خوبی نوشتی.", "👏 Well done, {name}! Nice sentence.", "👏 Gut gemacht, {name}! Schöner Satz.")
S("t_praise_2", "🌟 عالی بود {name}! این جمله درست و طبیعی است.", "🌟 Great job, {name}! That sentence is correct and natural.", "🌟 Super, {name}! Dieser Satz ist richtig und natürlich.")
S("t_praise_3", "😊 خیلی خوب {name}! همین‌طور ادامه بده.", "😊 Very good, {name}! Keep it up.", "😊 Sehr gut, {name}! Weiter so.")
S("t_polish_1", "🙂 {name}، تلاشت عالی است! فقط یک نکتهٔ کوچک:", "🙂 Nice effort, {name}! Just one small tip:", "🙂 Schön versucht, {name}! Nur ein kleiner Tipp:")
S("t_polish_2", "🌱 {name}، نزدیک بود! یک اصلاح کوچک:", "🌱 Close, {name}! One small fix:", "🌱 Fast, {name}! Eine kleine Korrektur:")
S("t_fix", "✏️ <b>{fixed}</b>", "✏️ <b>{fixed}</b>", "✏️ <b>{fixed}</b>")
S("t_why", "💡 {why}", "💡 {why}", "💡 {why}")
S("t_py", "🔤 <i>{py}</i>", "🔤 <i>{py}</i>", "🔤 <i>{py}</i>")
S("t_words", "📚 <b>واژه‌ها:</b>\n{lines}", "📚 <b>Words:</b>\n{lines}", "📚 <b>Wörter:</b>\n{lines}")
S("t_no_translate", "ℹ️ بدون هوش مصنوعی نمی‌توانم کل جمله را ترجمه یا همهٔ اشتباه‌ها را پیدا کنم؛ فقط الگوهای رایج را بررسی می‌کنم و معنی واژه‌ها را نشان می‌دهم.", "ℹ️ Without AI I can't translate whole sentences or catch every mistake; I only check a few common patterns and show the word meanings.", "ℹ️ Ohne KI kann ich ganze Sätze nicht übersetzen und nicht jeden Fehler finden; ich prüfe nur häufige Muster und zeige die Wortbedeutungen.")
S("t_follow_1", "❓ می‌توانی با «{w}» یک جملهٔ دیگر بسازی؟", "❓ Can you make another sentence with “{w}”?", "❓ Kannst du noch einen Satz mit „{w}“ bilden?")
S("t_follow_2", "❓ «{w}» را چطور در یک پرسش به کار می‌بری؟", "❓ How would you use “{w}” in a question?", "❓ Wie würdest du „{w}“ in einer Frage verwenden?")
S("t_follow_3", "❓ این جمله را با منفی (不/没) هم می‌توانی بگویی؟", "❓ Can you also say it in the negative (不/没)?", "❓ Kannst du den Satz auch verneinen (不/没)?")
S("t_encourage_1", "💪 چینی سخت به نظر می‌رسد ولی با تمرین کوچک روزانه راحت می‌شود. هر روز ۵ دقیقه کافی است!", "💪 Chinese can feel hard, but small daily practice makes it easy. Five minutes a day is enough!", "💪 Chinesisch wirkt schwer, aber kleine tägliche Übung hilft enorm. Fünf Minuten am Tag reichen!")
S("t_encourage_2", "🌟 هر کسی که شروع می‌کند حق دارد اشتباه کند؛ اشتباه یعنی در حال یادگرفتنی. ادامه بده!", "🌟 Mistakes are part of learning — you're doing great by trying. Keep going!", "🌟 Fehler gehören zum Lernen — toll, dass du dranbleibst. Weiter so!")
S("t_encourage_3", "🏮 یاد بگیر، تکرار کن، دوباره بگو. گام‌به‌گام جلو می‌رویم!", "🏮 Learn, repeat, say it again. We'll go step by step!", "🏮 Lernen, wiederholen, nochmal sagen. Schritt für Schritt!")
S("t_tip", "🎵 نکته: {tip}", "🎵 Tip: {tip}", "🎵 Tipp: {tip}")
S("t_btn_ex", "🧠 تمرین کوچک", "🧠 Mini-exercise", "🧠 Mini-Übung")
S("t_prompt_head", "🎓 <b>تمرین کوچک</b>", "🎓 <b>Mini-exercise</b>", "🎓 <b>Mini-Übung</b>")
S("t_prompt_hint", "↩️ جواب را روی همین پیام <b>ریپلای</b> کن.", "↩️ <b>Reply</b> to this message with your answer.", "↩️ <b>Antworte</b> auf diese Nachricht mit deiner Lösung.")
S("t_prompt_ok", "🎉 آفرین {name}! درست بود (+{pts})", "🎉 Well done, {name}! Correct (+{pts})", "🎉 Gut gemacht, {name}! Richtig (+{pts})")
S("t_prompt_bad", "🙂 تقریباً {name}، نگران نباش! جواب و توضیح:", "🙂 Not quite, {name} — no worries! Here is the answer and why:", "🙂 Nicht ganz, {name} — kein Problem! Hier Antwort und Erklärung:")
S("t_prompt_more", "➡️ یکی دیگر؟", "➡️ Another one?", "➡️ Noch eine?")
S("t_ai_note", "", "", "")
S("t_q_head", "🎓 سؤال خوبی بود {name}!", "🎓 Good question, {name}!", "🎓 Gute Frage, {name}!")
S("t_word_head", "📖 {name}، این هم معنی:", "📖 {name}, here you go:", "📖 {name}, bitteschön:")
S("t_sorry_ai", "الان نمی‌توانم با هوش مصنوعی جواب بدهم؛ پاسخ ساده:", "I can't reach the AI right now; here's a simpler answer:", "Ich erreiche die KI gerade nicht; hier eine einfachere Antwort:")

S("g_qs_quiz", "🧠 آزمون گروهی", "🧠 Group quiz", "🧠 Gruppen-Quiz")
S("g_qs_word", "📖 واژهٔ روز", "📖 Word of the day", "📖 Wort des Tages")
S("t_quickstart", "سلام {name}! 😊 من معلم چینی‌ام. با یکی از دکمه‌ها شروع کن، یا یک جملهٔ چینی / یک سؤال بنویس و با هم بررسی می‌کنیم.", "Hello {name}! 😊 I'm the Chinese teacher. Tap a button to start, or write a Chinese sentence or a question and we'll look at it together.", "Hallo {name}! 😊 Ich bin der Chinesisch-Lehrer. Tippe auf einen Button oder schreib einen chinesischen Satz bzw. eine Frage, dann schauen wir gemeinsam.")

import course_texts as _ct
_ct.add(S, _S)
import xtexts as _xt
_xt.add(S, _S)

T = {"fa": {}, "en": {}, "de": {}}
for _k, (_fa, _en, _de) in _S.items():
    T["fa"][_k], T["en"][_k], T["de"][_k] = _fa, _en, _de

def tr(_lang, _key, **kw):
    s = T.get(_lang, T["fa"])[_key]
    return s.format(**kw) if kw else s

LANG_LABEL = {"fa": "فارسی", "en": "English", "de": "Deutsch"}
