"""UI strings of the multi-language edition (generic bot texts + German/Russian course/alphabet/dictionary texts). Registered via add(S, _S)."""

def add(S, _S):
    def S2(key, fa, en, de=None): S(key, fa, en, de or en)      # German UI falls back to English for the long new texts
    # ---------------------------------------------------------------- generic (language-neutral) bot texts
    S("welcome",
      "👋 سلام! من <b>{name}</b> هستم، معلم خصوصی زبان برای فارسی‌زبان‌ها: 🇨🇳 چینی، 🇩🇪 آلمانی و 🇷🇺 روسی.\n\n🎯 از صفر شروع می‌کنی: الفبا و تلفظ، واژه‌های پایه، دستور، جمله، تمرین با اصلاح خطا و مرور هوشمند (لایتنر / SM-2).\n🌍 هر وقت خواستی زبان دیگری را هم اضافه کن یا بین زبان‌ها جابه‌جا شو: /lang\n👇 فقط یکی از دکمه‌ها را بزن. هر وقت خواستی یک واژه یا سؤال بفرست.",
      "👋 Hi! I'm <b>{name}</b>, your private language teacher: 🇨🇳 Chinese, 🇩🇪 German and 🇷🇺 Russian.\n\n🎯 Start from zero: alphabet & pronunciation, core vocabulary, grammar, sentences, exercises with corrections and smart review (Leitner / SM-2).\n🌍 Add another language or switch any time: /lang\n👇 Just tap a button. Send me any word or question any time.",
      "👋 Hallo! Ich bin <b>{name}</b>, dein privater Sprachlehrer: 🇨🇳 Chinesisch, 🇩🇪 Deutsch und 🇷🇺 Russisch.\n\n🎯 Starte bei null: Alphabet & Aussprache, Grundwortschatz, Grammatik, Sätze, Übungen mit Korrektur und smarte Wiederholung (Leitner / SM-2).\n🌍 Weitere Sprache hinzufügen oder wechseln: /lang\n👇 Tippe einfach auf einen Knopf. Schick mir jederzeit ein Wort oder eine Frage.")
    S("help",
      "ℹ️ <b>راهنما</b>\n\n🌍 /lang — زبان یادگیری (چینی / آلمانی / روسی)؛ هر زبان پیشرفت جدا دارد\n📅 /today — درس امروز (لغت جدید + مرور + تمرین)\n🎓 /course — دورهٔ قدم‌به‌قدم از صفر + 🎯 /placement تعیین سطح\n📖 /learn — یادگیری لغت‌های تازه\n🧠 /quiz — تمرین با انواع سؤال (اصلاح و توضیح خطاها)\n🔁 /review — مرور با جعبه لایتنر / SM-2\n🔍 /dict <i>واژه</i> — دیکشنری\n💬 /ask <i>سؤال</i> — پرسش دستور زبان و کاربرد\n🔤 /alphabet — الفبا، تلفظ و قواعد خواندن (چینی: پینیین و لحن؛ روسی: سیریلیک و تکیه؛ آلمانی: اومالوت و قواعد)\n📚 /read — داستان‌های کوتاه (فقط چینی)\n📊 /progress — پیشرفت و آمار\n⚙️ /settings — زبان ربات، سطح، یادآور\n\n💡 هر واژه‌ای بفرستی، در زبانِ فعالت دنبالش می‌گردم.\n\n⚠️ معنی‌های فارسی/انگلیسی آلمانی و روسی را خود پروژه نوشته و هنوز مترجم انسانی بازبینی نکرده؛ اگر اشتباهی دیدی با /settings ← گزارش به مدیر بگو.\n\n👥 <b>در گروه</b>: /quiz /word /dict /ask — یا ربات را منشن کن یا روی پیامش ریپلای بزن. زبان آموزشِ گروه را مدیر با /settings انتخاب می‌کند.",
      "ℹ️ <b>Help</b>\n\n🌍 /lang — learning language (Chinese / German / Russian); each language has its own progress\n📅 /today — today's lesson (new words + review + practice)\n🎓 /course — guided course from zero + 🎯 /placement test\n📖 /learn — learn new words\n🧠 /quiz — exercises of many types (with corrections and explanations)\n🔁 /review — Leitner / SM-2 review\n🔍 /dict <i>word</i> — dictionary\n💬 /ask <i>question</i> — grammar & usage questions\n🔤 /alphabet — alphabet, pronunciation and reading rules (Chinese: pinyin & tones; Russian: Cyrillic & stress; German: umlauts & rules)\n📚 /read — short stories (Chinese only)\n📊 /progress — progress & stats\n⚙️ /settings — bot language, level, reminder\n\n💡 Send any word and I'll look it up in your active language.\n\n⚠️ The Persian/English glosses for German and Russian were written by this project and have not yet been reviewed by a human translator; if you spot a mistake, tell the admin.\n\n👥 <b>In groups</b>: /quiz /word /dict /ask — or mention the bot / reply to its message. A group admin picks the group's language with /settings.",
      "ℹ️ <b>Hilfe</b>\n\n🌍 /lang — Lernsprache (Chinesisch / Deutsch / Russisch); jede Sprache hat eigenen Fortschritt\n📅 /today — heutige Lektion\n🎓 /course — geführter Kurs von null + 🎯 /placement Einstufungstest\n📖 /learn — neue Wörter\n🧠 /quiz — Übungen mit Korrektur\n🔁 /review — Leitner-/SM-2-Wiederholung\n🔍 /dict <i>Wort</i> — Wörterbuch\n💬 /ask <i>Frage</i> — Grammatik & Gebrauch\n🔤 /alphabet — Alphabet, Aussprache und Leseregeln\n📚 /read — Kurzgeschichten (nur Chinesisch)\n📊 /progress — Fortschritt\n⚙️ /settings — Bot-Sprache, Niveau, Erinnerung\n\n⚠️ Die persischen/englischen Bedeutungen für Deutsch und Russisch stammen vom Projekt selbst und wurden noch nicht von Muttersprachlern geprüft.\n\n👥 <b>In Gruppen</b>: /quiz /word /dict /ask — oder den Bot erwähnen / auf seine Nachricht antworten.")
    S("remind_msg",
      "⏰ وقت یادگیری زبان است! 🌍\n📚 {due} مرور سررسیده • 🔥 رگه: {streak} روز\nیک درس کوتاه امروز را بزن 👇",
      "⏰ Time to study! 🌍\n📚 {due} reviews due • 🔥 streak: {streak} days\nTap today's short lesson 👇",
      "⏰ Zeit zum Lernen! 🌍\n📚 {due} Wiederholungen fällig • 🔥 Serie: {streak} Tage\nTippe auf die heutige Kurzlektion 👇")
    S("g_intro",
      "👋 سلام به همه! من <b>{name}</b> هستم، معلم زبان 🇨🇳🇩🇪🇷🇺 (چینی، آلمانی، روسی)\n\n<b>چه کارهایی می‌کنم؟</b>\n🧠 /quiz — یک تمرین برای همهٔ گروه؛ اولین جواب درست امتیاز می‌گیرد\n📖 /word — واژهٔ روز با تلفظ و معنی\n🔍 /dict <i>واژه</i> — دیکشنری\n💬 /ask <i>سؤال</i> — دستور زبان و کاربرد\n🏆 /top — جدول امتیازات گروه\n\n<b>چطور با من حرف بزنیم؟</b>\n• با دستورها (مثلاً <code>/quiz@{bot}</code>)\n• من را منشن کنید: <code>@{bot} Schule</code>\n• روی پیام‌های من ریپلای بزنید\n\n<b>مدیران گروه:</b> با /settings <b>زبانِ آموزشِ گروه</b> (چینی / آلمانی / روسی)، زبان پیام‌ها، سطح، «واژهٔ روز» و روشن/خاموش بودن من را تنظیم کنید.\n🔒 پیشرفت شخصی هر نفر فقط در چت خصوصی خودش ثبت می‌شود و از گروه جداست.\n\n👇 برای یادگیری شخصی، چت خصوصی را باز کنید:",
      "👋 Hello everyone! I'm <b>{name}</b>, a language teacher 🇨🇳🇩🇪🇷🇺 (Chinese, German, Russian)\n\n<b>What I do:</b>\n🧠 /quiz — one exercise for the whole group; first correct answer scores\n📖 /word — word of the day with pronunciation and meaning\n🔍 /dict <i>word</i> — dictionary\n💬 /ask <i>question</i> — grammar & usage\n🏆 /top — group leaderboard\n\n<b>How to talk to me:</b>\n• Commands (e.g. <code>/quiz@{bot}</code>)\n• Mention me: <code>@{bot} Schule</code>\n• Reply to my messages\n\n<b>Group admins:</b> use /settings to set the group's <b>learning language</b> (Chinese / German / Russian), message language, level, “word of the day” and to enable/disable me.\n🔒 Each person's personal progress is stored only in their own private chat, separate from the group.\n\n👇 For personal learning, open the private chat:",
      "👋 Hallo zusammen! Ich bin <b>{name}</b>, ein Sprachlehrer 🇨🇳🇩🇪🇷🇺 (Chinesisch, Deutsch, Russisch)\n\n<b>Was ich kann:</b>\n🧠 /quiz — eine Übung für die ganze Gruppe\n📖 /word — Wort des Tages\n🔍 /dict <i>Wort</i> — Wörterbuch\n💬 /ask <i>Frage</i> — Grammatik\n🏆 /top — Rangliste\n\n• Befehle (z. B. <code>/quiz@{bot}</code>) oder Erwähnung: <code>@{bot} Schule</code>\n\n<b>Gruppenadmins:</b> /settings → Lernsprache der Gruppe, Nachrichtensprache, Niveau, „Wort des Tages“.\n🔒 Persönlicher Fortschritt bleibt im privaten Chat.\n\n👇 Zum persönlichen Lernen den privaten Chat öffnen:")
    S("progress",
      "📊 <b>پیشرفت تو</b> — {tl}\n\n👤 سطح: <b>{level}</b>\n⭐ امتیاز: <b>{xp}</b>\n🔥 رگه: <b>{streak}</b> روز (بهترین: {best})\n🎯 دقت: <b>{acc}٪</b> ({ok}/{tot})\n\n📚 لغات در حال یادگیری: <b>{cards}</b> • تسلط‌یافته: <b>{mast}</b>\n📦 جعبه‌ها: {boxes}\n📈 {plabel}\n❗ اشتباهات مرورنشده: <b>{mist}</b>\n🔁 مرورهای سررسیده: <b>{due}</b>",
      "📊 <b>Your progress</b> — {tl}\n\n👤 Level: <b>{level}</b>\n⭐ XP: <b>{xp}</b>\n🔥 Streak: <b>{streak}</b> days (best: {best})\n🎯 Accuracy: <b>{acc}%</b> ({ok}/{tot})\n\n📚 Words in learning: <b>{cards}</b> • mastered: <b>{mast}</b>\n📦 Boxes: {boxes}\n📈 {plabel}\n❗ Unreviewed mistakes: <b>{mist}</b>\n🔁 Reviews due: <b>{due}</b>",
      "📊 <b>Dein Fortschritt</b> — {tl}\n\n👤 Niveau: <b>{level}</b>\n⭐ XP: <b>{xp}</b>\n🔥 Serie: <b>{streak}</b> Tage (Rekord: {best})\n🎯 Genauigkeit: <b>{acc} %</b> ({ok}/{tot})\n\n📚 Wörter im Lernen: <b>{cards}</b> • gemeistert: <b>{mast}</b>\n📦 Boxen: {boxes}\n📈 {plabel}\n❗ Ungeprüfte Fehler: <b>{mist}</b>\n🔁 Fällige Wiederholungen: <b>{due}</b>")
    S("alpha_menu", "🔤 <b>آوا و حروف</b>\nیکی را انتخاب کن:", "🔤 <b>Sounds & letters</b>\nChoose one:", "🔤 <b>Laute & Buchstaben</b>\nWähle eins:")
    S("b_alpha", "🔤 الفبا و تلفظ", "🔤 Alphabet & sounds", "🔤 Alphabet & Laute")
    S("b_read", "📚 داستان کوتاه (چینی)", "📚 Short stories (Chinese)", "📚 Kurzgeschichten (Chinesisch)")
    S("tip_head", "💡 <b>نکتهٔ امروز</b>", "💡 <b>Tip of the day</b>", "💡 <b>Tipp des Tages</b>")
    # ---------------------------------------------------------------- language switching
    S2("b_lang", "🌍 زبان‌های من", "🌍 My languages", "🌍 Meine Sprachen")
    S2("pick_target", "🌍 <b>کدام زبان را می‌خواهی یاد بگیری؟</b>\nهر زبان پیشرفت، کارت‌های مرور و دورهٔ جدا دارد؛ بعداً با /lang می‌توانی زبان دیگری هم اضافه کنی یا جابه‌جا شوی.",
       "🌍 <b>Which language do you want to learn?</b>\nEvery language has its own progress, review cards and course; later you can add another or switch with /lang.",
       "🌍 <b>Welche Sprache möchtest du lernen?</b>\nJede Sprache hat eigenen Fortschritt, eigene Karten und einen eigenen Kurs; mit /lang kannst du später weitere hinzufügen oder wechseln.")
    S2("lang_menu", "🌍 <b>زبان‌های من</b>\nزبان فعال: {cur}\n\nروی یک زبان بزن تا فعالش کنی (پیشرفتِ جدا برای هر زبان نگه داشته می‌شود):",
       "🌍 <b>My languages</b>\nActive language: {cur}\n\nTap a language to make it active (each language keeps its own progress):",
       "🌍 <b>Meine Sprachen</b>\nAktive Sprache: {cur}\n\nTippe auf eine Sprache, um sie zu aktivieren (jede behält ihren Fortschritt):")
    S2("lang_switched", "✅ زبان فعال: {cur}\nپیشرفت، کارت‌های مرور و دورهٔ این زبان جدا از بقیه است.", "✅ Active language: {cur}\nProgress, review cards and course for this language are kept separate.", "✅ Aktive Sprache: {cur}\nFortschritt, Karten und Kurs dieser Sprache sind getrennt.")
    S2("lang_new_hint", "🆕 این زبان را برای اولین بار انتخاب کردی. از کجا شروع کنیم؟", "🆕 First time with this language. Where shall we start?", "🆕 Erstes Mal mit dieser Sprache. Wo fangen wir an?")
    S2("lang_tag", "{flag} {name}", "{flag} {name}", "{flag} {name}")
    S2("ob_target_done", "{cur} انتخاب شد.", "{cur} selected.", "{cur} gewählt.")
    S2("g_target", "🌍 زبان آموزشِ گروه: <b>{tl}</b>", "🌍 Group learning language: <b>{tl}</b>", "🌍 Lernsprache der Gruppe: <b>{tl}</b>")
    S2("b_g_target", "🌍 زبان آموزشی گروه", "🌍 Group learning language", "🌍 Lernsprache der Gruppe")
    S2("g_teacher_zh_only", "ℹ️ حالت «معلم» (تحلیل خودکار جمله) فقط برای چینی است؛ برای آلمانی و روسی از /quiz /word /dict /ask استفاده کنید.", "ℹ️ “Teacher mode” (automatic sentence analysis) is Chinese-only; for German and Russian use /quiz /word /dict /ask.", "ℹ️ Der „Lehrer-Modus“ (automatische Satzanalyse) gibt es nur für Chinesisch; für Deutsch und Russisch nutzt /quiz /word /dict /ask.")
    S2("zh_only", "ℹ️ این بخش فقط برای زبان چینی است. با /lang به چینی برو.", "ℹ️ This feature is Chinese-only. Switch to Chinese with /lang.", "ℹ️ Diese Funktion gibt es nur für Chinesisch. Wechsle mit /lang zu Chinesisch.")
    S2("tl_level_line", "{flag} {lv}", "{flag} {lv}", "{flag} {lv}")
    # ---------------------------------------------------------------- German / Russian course texts
    S2("cx_pick_path", "🧭 <b>{ln}: از کجا شروع کنیم؟</b>\n\n🎯 <b>تعیین سطح</b>: ۱۲ سؤال کوتاه می‌پرسم و بعد پیشنهاد می‌دهم از کجا شروع کنی.\n🌱 <b>از صفر مطلق</b>: دورهٔ قدم‌به‌قدم با من ({n} درس) — الفبا/تلفظ، واژه‌ها، دستور، جمله؛ هر درس: توضیح کوتاه ← تمرین با اصلاح ← درس بعد.\n🤷 <b>خودم انتخاب می‌کنم / نمی‌دانم</b>: سطحت را دستی انتخاب کن.",
       "🧭 <b>{ln}: where shall we start?</b>\n\n🎯 <b>Placement test</b>: 12 short questions, then I recommend where to start.\n🌱 <b>Absolute zero</b>: the guided step-by-step course with me ({n} lessons) — alphabet/pronunciation, words, grammar, sentences; each lesson: short explanation → practice with corrections → next lesson.\n🤷 <b>I'll choose / I don't know</b>: pick your level by hand.")
    S2("cx_zero_intro", "🌱 <b>{ln}: شروع از صفر</b>\nدورهٔ ما {n} درس دارد با ترتیب ثابت: تلفظ/الفبا ← واژه‌های A1 + دستور + جمله ← A2.\nهر درس: توضیح کوتاه ← تمرین با اصلاح ← با ≥ ۷۰٪ درست، درس بعدی باز می‌شود. هر وقت خواستی برگرد: /course",
       "🌱 <b>{ln}: starting from zero</b>\nThe course has {n} lessons in a fixed order: pronunciation/alphabet → A1 words + grammar + sentences → A2.\nEach lesson: short explanation → practice with corrections → with ≥ 70 % correct the next lesson unlocks. Come back any time: /course")
    S2("cx_place_intro", "🎯 <b>{ln}: تعیین سطح</b>\n{n} سؤال کوتاه: ۴ سؤال پایه، ۴ سؤال A1، ۴ سؤال A2. حدس زدن اشکال ندارد؛ فقط برای پیدا کردن نقطهٔ شروع است.",
       "🎯 <b>{ln}: placement test</b>\n{n} short questions: 4 basics, 4 at A1, 4 at A2. Guessing is fine; it's only to find your starting point.")
    S2("cx_tier0_de", "پایه (اولین واژه‌ها)", "Basics (first words)")
    S2("cx_tier0_ru", "الفبا و خواندن", "Alphabet & reading")
    S2("cx_rec_zero", "🌱 پایه هنوز محکم نیست؛ بهتر است از صفر شروع کنی.", "🌱 The basics aren't solid yet; best to start from zero.")
    S2("cx_rec_a1", "1️⃣ پایه را داری؛ از واژه‌ها و دستور A1 شروع کن.", "1️⃣ You have the basics; start with the A1 words and grammar.")
    S2("cx_rec_a2", "2️⃣ A1 را خوب می‌دانی؛ از A2 شروع کن.", "2️⃣ You know A1 well; start with A2.")
    S2("cx_rec_top", "🏆 عالی! از انتهای A2 شروع کن و بقیه را از فهرست مرور کن.", "🏆 Excellent! Start at the end of A2 and review the rest from the list.")
    S2("cx_alpha_tip", "💡 <b>نکته</b>\n• ь (علامت نرمی) صدای خودش را ندارد و همخوان قبلی را نرم می‌کند؛ ъ (علامت سختی) نادر است و بین دو بخش جدا می‌کند.\n• ы بعد از همخوان سخت می‌آید، и بعد از نرم.\n• ё همیشه تکیه‌دار است (نقطه‌ها معمولاً نوشته نمی‌شوند).\n• й مثل «ی» کوتاه در پایان مصوت است.",
       "💡 <b>Tips</b>\n• ь (soft sign) has no sound of its own; it softens the consonant before it. ъ (hard sign) is rare and separates two parts of a word.\n• ы follows a hard consonant, и a soft one.\n• ё is always stressed (the dots are usually not written).\n• й is a short “y” after a vowel.")
    S2("cx_soundcheck_body", "🎧 <b>مرور تلفظ</b>\nگوش بده و واژه‌ی درست را انتخاب کن؛ بعضی سؤال‌ها هم حرف‌ها را می‌خواهند.", "🎧 <b>Pronunciation checkpoint</b>\nListen and pick the right word; some questions ask about letters.")
    S2("cx_alpha_menu_ru", "🔤 <b>روسی: الفبا و تلفظ</b>\nسیریلیک (۳۳ حرف)، قواعد خواندن، تکیه و نرم/سخت.", "🔤 <b>Russian: alphabet & pronunciation</b>\nCyrillic (33 letters), reading rules, stress and soft/hard.")
    S2("cx_alpha_menu_de", "🔤 <b>آلمانی: تلفظ و املا</b>\nاومالوت، ß، ch، sch/sp/st، ei/ie/eu و ...", "🔤 <b>German: pronunciation & spelling</b>\nUmlauts, ß, ch, sch/sp/st, ei/ie/eu and more.")
    S2("cx_b_letters", "🔤 حروف سیریلیک", "🔤 Cyrillic letters")
    S2("cx_b_rules", "📏 قواعد خواندن", "📏 Reading rules")
    S2("cx_b_sounds", "🎧 تلفظ و قواعد", "🎧 Sounds & rules")
    S2("cx_dict_prompt", "🔍 یک واژه بفرست: {ex} یا معنی فارسی/انگلیسی. <i>فقط فهرست دست‌چین‌شدهٔ A1–A2 جستجو می‌شود.</i>", "🔍 Send a word: {ex}, or a Persian/English meaning. <i>Only the curated A1–A2 list is searched.</i>")
    S2("cx_dict_none", "😕 «{q}» در فهرست دست‌چین A1–A2 نیست. <i>دیکشنری آلمانی/روسی عمداً کوچک است؛ هنوز دیکشنری کامل نیست.</i>", "😕 “{q}” is not in the curated A1–A2 list. <i>The German/Russian dictionary is deliberately small; it is not a full dictionary yet.</i>")
    S2("cx_mock", "📝 آزمون سطح", "📝 Level test")
    S2("cx_mock_intro", "📝 <b>آزمون سطح ({lv})</b>\n۱۰ سؤال ترکیبی؛ نمره در پایان. زمان محدود نیست. موفق باشی!", "📝 <b>Level test ({lv})</b>\n10 mixed questions; score at the end. No time limit. Good luck!")
    S2("cx_mock_done", "📝 <b>نتیجهٔ آزمون سطح ({lv})</b>\n✅ {ok} از {n} → <b>{pct}٪</b>\n{grade}", "📝 <b>Level test result ({lv})</b>\n✅ {ok} of {n} → <b>{pct}%</b>\n{grade}")
    S2("cx_ask_none", "پاسخ مشخصی پیدا نکردم. یک واژه را به /dict بفرست یا دربارهٔ یک مبحث بپرس، مثلاً: der/die/das، حالت‌ها، تکیه، فعل‌های حرکت.", "I couldn't find a specific answer. Try /dict for a word, or ask about a topic such as articles, cases, stress, verbs of motion.")
    S2("cx_gloss_note", "ℹ️ معنی‌های فارسی و انگلیسی آلمانی/روسی ساختهٔ خود پروژه‌اند و هنوز توسط مترجم/معلم بازبینی نشده‌اند.", "ℹ️ The Persian and English meanings for German/Russian are the project's own and have not yet been reviewed by a translator or teacher.")
    S2("cx_levels_line", "{a1} · {a2}", "{a1} · {a2}")
    S2("cx_progress_levels", "{flag} A1: {p1} • A2: {p2}", "{flag} A1: {p1} • A2: {p2}")
    S2("cx_no_new", "🏆 واژهٔ تازه‌ای در این سطح نمانده! سطحت را بالا ببر یا مرور کن.", "🏆 No new words left at this level! Raise your level or review.")
    S2("cx_lvl_0", "🌱 مبتدی (صفر)", "🌱 Absolute beginner")
    S2("cx_lvl_1", "A1", "A1")
    S2("cx_lvl_2", "A2", "A2")
