"""Authored teaching content (grammar tips, idioms, culture, graded readers). Strings are (fa, en, de) tuples."""

# id, keywords for rule-based Q&A, pattern, example zh, example pinyin, (title fa,en,de), (body fa,en,de), (example translation fa,en,de)
GRAMMAR = [
 ("order", ["word order", "ترتیب", "sov", "svo", "reihenfolge", "satzbau"], "主语 + 动词 + 宾语", "我喝茶。", "Wǒ hē chá.",
  ("ترتیب جمله", "Basic word order", "Grundlegende Wortstellung"),
  ("ترتیب جمله در چینی مثل انگلیسی «فاعل + فعل + مفعول» است (نه فعل در آخر مثل فارسی). فعل صرف نمی‌شود؛ زمان با واژه‌های زمانی و نشانه‌ها (了، 过، 在) می‌آید.",
   "Chinese is Subject + Verb + Object (the verb does NOT go last as in Persian). Verbs never conjugate; time is shown with time words and particles (了, 过, 在).",
   "Chinesisch ist Subjekt + Verb + Objekt (das Verb steht NICHT am Ende wie im Persischen). Verben werden nicht konjugiert; Zeit wird durch Zeitwörter und Partikeln (了, 过, 在) ausgedrückt."),
  ("من چای می‌نوشم.", "I drink tea.", "Ich trinke Tee.")),
 ("shi", ["是", "to be", "بودن", "sein"], "A 是 B", "他是老师。", "Tā shì lǎoshī.",
  ("فعل «是» (بودن)", "The verb 是 (to be)", "Das Verb 是 (sein)"),
  ("«是» بین دو اسم می‌آید: A 是 B. برای صفت معمولاً «是» نمی‌آید؛ از «很» استفاده کن: 她很高兴. نفی: 不是.",
   "是 links two nouns: A 是 B. With adjectives don't use 是; use 很: 她很高兴. Negative: 不是.",
   "是 verbindet zwei Nomen: A 是 B. Bei Adjektiven kein 是, sondern 很: 她很高兴. Verneinung: 不是."),
  ("او معلم است.", "He is a teacher.", "Er ist Lehrer.")),
 ("hen", ["很", "adjective", "صفت", "adjektiv", "very", "خیلی"], "主语 + 很 + 形容词", "今天很热。", "Jīntiān hěn rè.",
  ("صفت با «很»", "Adjectives with 很", "Adjektive mit 很"),
  ("صفت‌ها خودشان فعل‌اند و بدون «是» می‌آیند. معمولاً «很» قبل از صفت می‌آید (حتی وقتی معنی «خیلی» قوی نیست): 我很好.",
   "Adjectives act as verbs, no 是 needed. Put 很 before them (it is often weak, not really “very”): 我很好.",
   "Adjektive wirken wie Verben, ohne 是. Setze 很 davor (oft nur schwach „sehr“): 我很好."),
  ("امروز گرم است.", "It is hot today.", "Heute ist es heiß.")),
 ("ma", ["吗", "question", "سوال", "پرسش", "frage", "yes/no", "آیا"], "陈述句 + 吗？", "你喝茶吗？", "Nǐ hē chá ma?",
  ("سؤال بله/خیر با «吗»", "Yes/no questions with 吗", "Ja/Nein-Fragen mit 吗"),
  ("برای ساختن پرسش «آیا»، فقط «吗» را آخر جمله بگذار؛ ترتیب جمله تغییر نمی‌کند. شکل دیگر: «فعل + 不 + فعل»: 你喝不喝茶؟",
   "Add 吗 at the end of a statement to ask a yes/no question; word order doesn't change. Alternative: verb-not-verb: 你喝不喝茶?",
   "Hänge 吗 ans Satzende für eine Ja/Nein-Frage; die Wortstellung bleibt. Alternative: Verb-nicht-Verb: 你喝不喝茶?"),
  ("چای می‌نوشی؟", "Do you drink tea?", "Trinkst du Tee?")),
 ("bu_mei", ["不", "没", "negation", "نفی", "منفی", "verneinung", "méi", "bù"], "不 + 动词 / 没(有) + 动词", "我不去。我没吃饭。", "Wǒ bú qù. Wǒ méi chī fàn.",
  ("نفی: 不 و 没", "Negation: 不 vs 没", "Verneinung: 不 vs 没"),
  ("«不» برای نفی حال/آینده و عادت و خواست؛ «没(有)» برای نفی گذشته (انجام نشده) و فعل «有». «不» قبل از لحن ۴ می‌شود bú.",
   "不 negates present/future/habit/will; 没(有) negates the past (didn't happen) and 有. 不 becomes bú before a 4th tone.",
   "不 verneint Gegenwart/Zukunft/Gewohnheit/Willen; 没(有) verneint Vergangenes (nicht geschehen) und 有. 不 wird vor dem 4. Ton zu bú."),
  ("من نمی‌روم. من غذا نخوردم.", "I won't go. I didn't eat.", "Ich gehe nicht. Ich habe nicht gegessen.")),
 ("le", ["了", "le", "past", "گذشته", "perfective", "vergangenheit", "completed"], "动词 + 了", "我买了一本书。", "Wǒ mǎi le yì běn shū.",
  ("نشانهٔ «了»", "The particle 了", "Die Partikel 了"),
  ("«了» بعد از فعل یعنی کار «انجام و کامل شد». آخر جمله یعنی «وضعیت تازه». گذشته‌ی ساده نیست؛ برای گذشتهٔ کلی بدون 了 هم می‌شود. نفی: 没 (بدون 了): 我没买.",
   "了 after a verb marks a completed action; at sentence end it marks a change of state. It is not just “past tense”. Negation: 没 (drop 了): 我没买.",
   "了 nach dem Verb markiert eine abgeschlossene Handlung; am Satzende einen neuen Zustand. Es ist nicht einfach „Vergangenheit“. Verneinung: 没 (ohne 了): 我没买."),
  ("من یک کتاب خریدم.", "I bought a book.", "Ich habe ein Buch gekauft.")),
 ("de", ["的", "de", "possess", "مالکیت", "besitz", "attributive"], "A 的 B", "我的朋友是老师。", "Wǒ de péngyou shì lǎoshī.",
  ("«的» (مالکیت و وصف)", "的 (possession & modifier)", "的 (Besitz & Attribut)"),
  ("«的» مثل کسرهٔ اضافه است: «A 的 B» = B متعلق به A / B با ویژگی A. برای خویشاوندان و نهادهای نزدیک اغلب حذف می‌شود: 我妈妈.",
   "的 works like the Persian ezafe/“’s”: A 的 B = B of A. Often dropped with close relations: 我妈妈.",
   "的 entspricht dem Genitiv/„von“: A 的 B = B von A. Bei nahen Verwandten oft weggelassen: 我妈妈."),
  ("دوست من معلم است.", "My friend is a teacher.", "Mein Freund ist Lehrer.")),
 ("measure", ["量词", "measure", "classifier", "شمارنده", "کلمه شمارشی", "zählwort", "个"], "数 + 量词 + 名词", "三个人，两本书，一杯茶", "sān gè rén, liǎng běn shū, yì bēi chá",
  ("کلمهٔ شمارشی (量词)", "Measure words (量词)", "Zählwörter (量词)"),
  ("بین عدد و اسم باید کلمهٔ شمارشی بیاید: 个 (عمومی)، 本 (کتاب)، 杯 (لیوان)، 只 (حیوان کوچک)، 张 (چیز تخت)، 件 (لباس/کار). «二» قبل از آن‌ها «两» می‌شود: 两个人.",
   "Between a number and a noun you need a measure word: 个 (general), 本 (books), 杯 (cups), 只 (small animals), 张 (flat things), 件 (clothes/matters). “2” becomes 两 before them: 两个人.",
   "Zwischen Zahl und Nomen steht ein Zählwort: 个 (allgemein), 本 (Bücher), 杯 (Tassen), 只 (kleine Tiere), 张 (flache Dinge), 件 (Kleidung/Angelegenheiten). „2“ wird davor 两: 两个人."),
  ("سه نفر، دو کتاب، یک لیوان چای", "three people, two books, a cup of tea", "drei Personen, zwei Bücher, eine Tasse Tee")),
 ("zai", ["在", "zài", "location", "مکان", "ort", "progressive", "در حال"], "在 + 地点 / 在 + 动词", "我在家。我在学习。", "Wǒ zài jiā. Wǒ zài xuéxí.",
  ("«在» (مکان و در حال انجام)", "在 (location & progressive)", "在 (Ort & Verlaufsform)"),
  ("«在 + مکان» یعنی «در/هست». «在 + فعل» یعنی «در حال انجام کاری هستم». «在» قبل از فعل اصلی می‌آید: 我在北京工作.",
   "在 + place = “at/in”. 在 + verb = “in the middle of doing”. 在 goes before the main verb: 我在北京工作.",
   "在 + Ort = „in/an“. 在 + Verb = „gerade dabei“. 在 steht vor dem Hauptverb: 我在北京工作."),
  ("من خانه‌ام. دارم درس می‌خوانم.", "I am at home. I am studying.", "Ich bin zu Hause. Ich lerne gerade.")),
 ("you", ["有", "yǒu", "have", "داشتن", "haben", "there is", "وجود"], "有 / 没有", "我有一只猫。你有没有钱？", "Wǒ yǒu yì zhī māo. Nǐ yǒu méiyǒu qián?",
  ("«有» (داشتن/وجود داشتن)", "有 (to have / there is)", "有 (haben / es gibt)"),
  ("نفی «有» همیشه «没有» است (نه 不有). پرسش: 有没有؟ یا با 吗.", "The negative of 有 is always 没有 (never 不有). Question: 有没有? or with 吗.", "Die Verneinung von 有 ist immer 没有 (nie 不有). Frage: 有没有? oder mit 吗."),
  ("من یک گربه دارم. پول داری؟", "I have a cat. Do you have money?", "Ich habe eine Katze. Hast du Geld?")),
 ("bi", ["比", "compar", "مقایسه", "vergleich", "than", "از"], "A 比 B + صفت", "他比我高。", "Tā bǐ wǒ gāo.",
  ("مقایسه با «比»", "Comparison with 比", "Vergleich mit 比"),
  ("A 比 B + صفت = A از B ... تر است. قبل از صفت «很» نمی‌آید. اختلاف را بعد از صفت بگذار: 高一点儿 / 高三厘米. نفی: A 没有 B + صفت.",
   "A 比 B + adjective = A is more … than B. Don't use 很 before the adjective. Put the difference after it: 高一点儿. Negative: A 没有 B + adj.",
   "A 比 B + Adjektiv = A ist … als B. Kein 很 vor dem Adjektiv. Unterschied danach: 高一点儿. Verneinung: A 没有 B + Adj."),
  ("او از من قدبلندتر است.", "He is taller than me.", "Er ist größer als ich.")),
 ("hui_neng", ["会", "能", "可以", "can", "توانستن", "können", "modal"], "会 / 能 / 可以 + 动词", "我会说汉语。我能来。这里可以坐。", "Wǒ huì shuō Hànyǔ. Wǒ néng lái. Zhèlǐ kěyǐ zuò.",
  ("سه «می‌توانم»: 会، 能، 可以", "Three “can”s: 会, 能, 可以", "Drei „können“: 会, 能, 可以"),
  ("会 = بلد بودن (مهارت یادگرفته‌شده). 能 = توانایی/امکان. 可以 = اجازه. هر سه قبل از فعل می‌آیند.",
   "会 = know how to (learned skill). 能 = be able to (ability/possibility). 可以 = may (permission). All go before the verb.",
   "会 = können (erlernt). 能 = fähig/möglich sein. 可以 = dürfen. Alle stehen vor dem Verb."),
  ("من چینی بلدم. می‌توانم بیایم. اینجا می‌شود نشست.", "I can speak Chinese. I'm able to come. You may sit here.", "Ich kann Chinesisch. Ich kann kommen. Hier darf man sitzen.")),
 ("guo", ["过", "guò", "experience", "تجربه", "erfahrung", "ever"], "动词 + 过", "我去过中国。", "Wǒ qù guo Zhōngguó.",
  ("تجربه با «过»", "Experience with 过", "Erfahrung mit 过"),
  ("«过» بعد از فعل یعنی «تا حالا تجربه کرده‌ام». نفی: 没 + فعل + 过.", "过 after a verb means “have ever done”. Negative: 没 + verb + 过.", "过 nach dem Verb heißt „schon mal getan“. Verneinung: 没 + Verb + 过."),
  ("من به چین رفته‌ام.", "I have been to China.", "Ich war schon in China.")),
 ("ba", ["把", "bǎ", "disposal", "مفعول"], "主语 + 把 + 宾语 + 动词 + 结果", "请把门关上。", "Qǐng bǎ mén guān shàng.",
  ("ساختار «把»", "The 把 construction", "Die 把-Konstruktion"),
  ("«把» مفعول را جلوی فعل می‌آورد تا بگوید با آن چه کار شد. فعل باید نتیجه/جهت داشته باشد (关上، 吃完). سطح HSK3.",
   "把 moves the object before the verb to say what was done to it. The verb needs a result/direction (关上, 吃完). HSK 3 level.",
   "把 stellt das Objekt vor das Verb, um zu sagen, was damit geschah. Das Verb braucht ein Resultat (关上, 吃完). HSK-3-Niveau."),
  ("لطفاً در را ببند.", "Please close the door.", "Bitte schließen Sie die Tür.")),
 ("bei", ["被", "bèi", "passive", "مجهول", "passiv"], "A 被 B + 动词", "我的钱包被偷了。", "Wǒ de qiánbāo bèi tōu le.",
  ("مجهول با «被»", "Passive with 被", "Passiv mit 被"),
  ("«被» جملهٔ مجهول می‌سازد (بیشتر برای اتفاق بد یا ناخوشایند). فاعل می‌تواند حذف شود. فعل معمولاً «了» یا نتیجه دارد.",
   "被 makes the passive (often for unpleasant events). The agent may be omitted. The verb usually has 了 or a result.",
   "被 bildet das Passiv (oft bei unangenehmen Ereignissen). Der Handelnde kann fehlen. Das Verb hat meist 了 oder ein Resultat."),
  ("کیف پولم دزدیده شد.", "My wallet was stolen.", "Mein Portemonnaie wurde gestohlen.")),
 ("shide", ["是的", "是...的", "shì de", "emphasis"], "是 + 时间/地点/方式 + 动词 + 的", "我是昨天来的。", "Wǒ shì zuótiān lái de.",
  ("ساختار «是…的»", "The 是…的 construction", "Die 是…的-Konstruktion"),
  ("برای تأکید بر زمان، مکان یا شیوهٔ کاری که قبلاً انجام شده: «是» قبل از جزء مورد تأکید و «的» آخر جمله.", "To stress when/where/how a past event happened: 是 before the emphasised part, 的 at the end.", "Zur Betonung von Zeit/Ort/Art eines vergangenen Ereignisses: 是 vor dem betonten Teil, 的 am Ende."),
  ("من «دیروز» آمدم.", "It was yesterday that I came.", "Ich bin gestern gekommen.")),
 ("yue", ["越来越", "more and more", "هرچه", "immer"], "越来越 + 形容词", "天气越来越冷。", "Tiānqì yuè lái yuè lěng.",
  ("«越来越» (روزبه‌روز…تر)", "越来越 (more and more)", "越来越 (immer mehr)"),
  ("«越来越 + صفت» یعنی «کم‌کم/روزبه‌روز بیشتر». «越…越…» یعنی «هرچه … بیشتر، … بیشتر».", "越来越 + adj = more and more. 越…越… = the more … the more ….", "越来越 + Adj = immer mehr. 越…越… = je mehr …, desto mehr …."),
  ("هوا روزبه‌روز سردتر می‌شود.", "It's getting colder and colder.", "Es wird immer kälter.")),
 ("yinwei", ["因为", "所以", "because", "چون", "weil", "但是", "虽然", "although"], "因为…所以… / 虽然…但是…", "因为下雨，所以我不去。", "Yīnwèi xià yǔ, suǒyǐ wǒ bú qù.",
  ("جمله‌های ربطی", "Linking clauses", "Verbindende Satzglieder"),
  ("چینی دو واژهٔ ربط را با هم می‌آورد: 因为…所以… (چون…پس…) و 虽然…但是… (هرچند…اما…). فارسی‌زبان‌ها اغلب یکی را حذف می‌کنند؛ در چینی هر دو رواست.",
   "Chinese pairs connectors: 因为…所以… (because…so…), 虽然…但是… (although…but…). Both halves are normal in Chinese.",
   "Chinesisch paart Konnektoren: 因为…所以… (weil…deshalb…), 虽然…但是… (obwohl…aber…). Beide Hälften sind üblich."),
  ("چون باران می‌آید، نمی‌روم.", "Because it's raining, I'm not going.", "Weil es regnet, gehe ich nicht.")),
 ("time", ["时间", "time order", "ترتیب زمان", "zeit", "when"], "时间 + 地点 + 动词", "我明天在家学习。", "Wǒ míngtiān zài jiā xuéxí.",
  ("جای زمان و مکان", "Placement of time & place", "Stellung von Zeit & Ort"),
  ("ترتیب: فاعل + زمان + مکان + فعل. زمان «قبل» از فعل می‌آید (نه آخر جمله): 我明天去.", "Order: subject + time + place + verb. Time goes BEFORE the verb (not at the end): 我明天去.", "Reihenfolge: Subjekt + Zeit + Ort + Verb. Die Zeit steht VOR dem Verb: 我明天去."),
  ("فردا در خانه درس می‌خوانم.", "Tomorrow I study at home.", "Morgen lerne ich zu Hause.")),
]

# chengyu: 4 chars, pinyin, meaning (fa, en, de), literal (en)
CHENGYU = [
 ("一石二鸟", "yì shí èr niǎo", ("با یک تیر دو نشان زدن", "to kill two birds with one stone", "zwei Fliegen mit einer Klappe schlagen"), "one stone, two birds"),
 ("画蛇添足", "huà shé tiān zú", ("کار زائد کردن که خرابش می‌کند", "to ruin it by adding something unnecessary", "etwas Überflüssiges hinzufügen und es verderben"), "draw a snake and add feet"),
 ("守株待兔", "shǒu zhū dài tù", ("به شانس تکیه کردن و دست روی دست گذاشتن", "to wait idly for luck instead of working", "untätig auf das Glück warten"), "guard a stump, wait for a rabbit"),
 ("亡羊补牢", "wáng yáng bǔ láo", ("هنوز دیر نشده؛ بعد از اشتباه جبران کن", "better late than never: fix things after a loss", "besser spät als nie: nach dem Verlust reparieren"), "mend the pen after the sheep is lost"),
 ("对牛弹琴", "duì niú tán qín", ("برای خر چنگ زدن؛ حرف زدن با کسی که نمی‌فهمد", "to play the lute to a cow: speaking to the wrong audience", "Perlen vor die Säue werfen"), "play the zither to an ox"),
 ("井底之蛙", "jǐng dǐ zhī wā", ("آدم کوته‌بین", "a narrow-minded person", "jemand mit engem Horizont"), "frog at the bottom of a well"),
 ("掩耳盗铃", "yǎn ěr dào líng", ("فریب دادن خود (به روی خود نیاوردن)", "to deceive oneself", "sich selbst etwas vormachen"), "cover ears to steal a bell"),
 ("杯弓蛇影", "bēi gōng shé yǐng", ("ترس بی‌دلیل؛ از سایهٔ خود ترسیدن", "groundless fear; being afraid of shadows", "unbegründete Angst; sich vor Schatten fürchten"), "bow in the cup, snake shadow"),
 ("半途而废", "bàn tú ér fèi", ("نیمه‌کاره رها کردن", "to give up halfway", "auf halbem Weg aufgeben"), "give up halfway"),
 ("一心一意", "yì xīn yí yì", ("با تمام وجود، یکدل", "wholeheartedly", "mit ganzem Herzen"), "one heart, one mind"),
 ("入乡随俗", "rù xiāng suí sú", ("در شهر کوران یک‌چشمی باش؛ با رسوم محل هماهنگ شو", "when in Rome, do as the Romans do", "andere Länder, andere Sitten"), "enter a village, follow its customs"),
 ("百闻不如一见", "bǎi wén bù rú yí jiàn", ("شنیدن کی بود مانند دیدن", "seeing once beats hearing a hundred times", "einmal sehen ist besser als hundertmal hören"), "hear 100 times is not like seeing once"),
 ("马马虎虎", "mǎ mǎ hū hū", ("سرسری؛ نه خوب نه بد (دم‌دستی)", "so-so; careless", "so lala; nachlässig"), "horse horse tiger tiger"),
 ("九牛一毛", "jiǔ niú yì máo", ("ناچیز؛ یک تار مو از نه گاو", "a drop in the ocean", "ein Tropfen auf den heißen Stein"), "one hair from nine oxen"),
 ("塞翁失马", "sài wēng shī mǎ", ("شاید در بدبختی خیری باشد", "a blessing in disguise", "Glück im Unglück"), "the old man lost his horse"),
 ("三心二意", "sān xīn èr yì", ("دودل؛ بی‌ثبات", "half-hearted; undecided", "unentschlossen; halbherzig"), "three hearts, two minds"),
]

CULTURE = [
 (("جشن بهار (春节)", "Spring Festival (春节)", "Frühlingsfest (春节)"),
  ("مهم‌ترین جشن چین، نوروز چینی بر اساس تقویم قمری-خورشیدی. خانواده دور هم جمع می‌شوند، «红包» (پاکت قرمز پول) می‌دهند و می‌گویند 新年快乐 (xīnnián kuàilè).",
   "China's most important holiday, based on the lunisolar calendar. Families reunite, give 红包 (red envelopes) and say 新年快乐 (xīnnián kuàilè).",
   "Das wichtigste Fest Chinas nach dem Mondsonnenkalender. Familien kommen zusammen, schenken 红包 (rote Umschläge) und sagen 新年快乐 (xīnnián kuàilè).")),
 (("چای در فرهنگ چینی (茶)", "Tea culture (茶)", "Teekultur (茶)"),
  ("چای نوشیدنی مهمان‌نوازی است. هنگام ریختن چای برای دیگران، با دو انگشت روی میز ضربه می‌زنند تا تشکر کنند. واژهٔ «茶» (chá) به فارسی «چای» شد.",
   "Tea is the drink of hospitality. When someone pours tea for you, tap two fingers on the table to say thanks. The word 茶 (chá) became Persian «چای».",
   "Tee ist das Getränk der Gastfreundschaft. Wenn jemand dir Tee einschenkt, klopfst du mit zwei Fingern auf den Tisch als Dank. Das Wort 茶 (chá) wurde persisch «چای».")),
 (("عدد خوش‌یمن ۸ و بدیمن ۴", "Lucky 8, unlucky 4", "Glückszahl 8, Unglückszahl 4"),
  ("عدد 八 (bā) شبیه 发 (fā، ثروتمند شدن) خوانده می‌شود پس خوش‌یمن است. عدد 四 (sì) شبیه 死 (sǐ، مرگ) است و دوست‌داشته نمی‌شود.",
   "八 (bā) sounds like 发 (fā, to get rich), so it is lucky. 四 (sì) sounds like 死 (sǐ, death) and is avoided.",
   "八 (bā) klingt wie 发 (fā, reich werden) und bringt Glück. 四 (sì) klingt wie 死 (sǐ, Tod) und wird gemieden.")),
 (("نام‌های چینی", "Chinese names", "Chinesische Namen"),
  ("اول نام خانوادگی می‌آید بعد نام: 王明 = خانوادگی 王 (Wáng) + نام 明 (Míng). نام‌ها معمولاً معنی دارند. پرسش مؤدبانه: 您贵姓؟ (nín guì xìng).",
   "The family name comes first: 王明 = surname 王 (Wáng) + given name 明 (Míng). Names usually have meanings. Polite question: 您贵姓? (nín guì xìng).",
   "Der Familienname steht zuerst: 王明 = Familienname 王 (Wáng) + Vorname 明 (Míng). Namen haben meist eine Bedeutung. Höflich fragen: 您贵姓? (nín guì xìng).")),
 (("چاپستیک (筷子)", "Chopsticks (筷子)", "Essstäbchen (筷子)"),
  ("چاپستیک را هرگز عمودی در کاسهٔ برنج فرو نکن؛ شبیه عود مراسم ترحیم است. همچنین با چاپستیک به کسی اشاره نکن.",
   "Never stick chopsticks upright in a rice bowl; it resembles funeral incense. Also don't point at people with them.",
   "Stecke Stäbchen niemals senkrecht in den Reis; das erinnert an Trauerweihrauch. Zeige auch nicht damit auf Menschen.")),
 (("حروف چینی و تاریخ", "Characters & history", "Schriftzeichen & Geschichte"),
  ("نوشتار چینی بیش از ۳۰۰۰ سال قدمت دارد. در ۱۹۵۰–۱۹۶۰ در چین اصلی «ساده‌شده» (简体字) رایج شد؛ تایوان و هنگ‌کنگ سنتی (繁體字) را نگه داشتند. این ربات ساده‌شده را آموزش می‌دهد.",
   "Chinese writing is over 3000 years old. In the 1950s–60s mainland China adopted Simplified characters (简体字); Taiwan and Hong Kong kept Traditional (繁體字). This bot teaches Simplified.",
   "Die chinesische Schrift ist über 3000 Jahre alt. In den 1950er–60er Jahren führte das Festland Kurzzeichen (简体字) ein; Taiwan und Hongkong behielten Langzeichen (繁體字). Dieser Bot lehrt Kurzzeichen.")),
 (("احوال‌پرسی: «吃了吗؟»", "Greeting: “吃了吗?”", "Begrüßung: „吃了吗?“"),
  ("به‌جای «حالت چطوره؟» گاهی می‌پرسند 吃了吗؟ (chī le ma؟ = غذا خوردی؟). مثل «خسته نباشید» نشانهٔ مهربانی است و لازم نیست جدی جواب بدهی.",
   "Instead of “how are you?” people sometimes ask 吃了吗? (chī le ma? = have you eaten?). It's a friendly greeting, not a real invitation.",
   "Statt „Wie geht's?“ fragt man manchmal 吃了吗? (chī le ma? = Hast du schon gegessen?). Das ist ein freundlicher Gruß, keine Einladung.")),
 (("پینیین چیست؟", "What is pinyin?", "Was ist Pinyin?"),
  ("پینیین (拼音) نظام لاتین‌نویسی تلفظ ماندارین است که در ۱۹۵۸ رسمی شد. با آن تلفظ و لحن را یاد می‌گیری و در گوشی چینی تایپ می‌کنی.",
   "Pinyin (拼音) is the Latin-letter system for Mandarin pronunciation, made official in 1958. You learn sounds and tones with it and type Chinese on phones.",
   "Pinyin (拼音) ist die lateinische Lautschrift für Mandarin, 1958 offiziell eingeführt. Damit lernst du Laute und Töne und tippst Chinesisch am Handy.")),
]

# graded readers: id, level, title (zh, fa, en, de), lines: list of (zh, pinyin, fa, en, de)
READERS = [
 ("r1", 1, ("我的一天", "یک روز من", "My day", "Mein Tag"), [
   ("我叫小明。", "Wǒ jiào Xiǎo Míng.", "اسم من شیائو مینگ است.", "My name is Xiao Ming.", "Ich heiße Xiao Ming."),
   ("我是学生。", "Wǒ shì xuésheng.", "من دانش‌آموزم.", "I am a student.", "Ich bin Schüler."),
   ("我早上八点去学校。", "Wǒ zǎoshang bā diǎn qù xuéxiào.", "صبح ساعت هشت به مدرسه می‌روم.", "I go to school at eight in the morning.", "Ich gehe morgens um acht zur Schule."),
   ("中午我吃米饭。", "Zhōngwǔ wǒ chī mǐfàn.", "ظهر برنج می‌خورم.", "At noon I eat rice.", "Mittags esse ich Reis."),
   ("晚上我看电视。", "Wǎnshang wǒ kàn diànshì.", "شب تلویزیون تماشا می‌کنم.", "In the evening I watch TV.", "Abends sehe ich fern."),
 ]),
 ("r2", 1, ("我的家", "خانوادهٔ من", "My family", "Meine Familie"), [
   ("我家有四个人。", "Wǒ jiā yǒu sì gè rén.", "خانوادهٔ من چهار نفر است.", "There are four people in my family.", "In meiner Familie sind vier Personen."),
   ("爸爸、妈妈、哥哥和我。", "Bàba, māma, gēge hé wǒ.", "پدر، مادر، برادر بزرگ و من.", "Dad, mom, older brother and me.", "Papa, Mama, großer Bruder und ich."),
   ("爸爸是医生。", "Bàba shì yīshēng.", "پدرم پزشک است.", "My dad is a doctor.", "Mein Vater ist Arzt."),
   ("妈妈是老师。", "Māma shì lǎoshī.", "مادرم معلم است.", "My mom is a teacher.", "Meine Mutter ist Lehrerin."),
   ("我们都很高兴。", "Wǒmen dōu hěn gāoxìng.", "ما همه خیلی خوشحالیم.", "We are all very happy.", "Wir sind alle sehr glücklich."),
 ]),
 ("r3", 2, ("去商店", "رفتن به فروشگاه", "Going shopping", "Einkaufen gehen"), [
   ("今天是星期六，我想去商店。", "Jīntiān shì xīngqīliù, wǒ xiǎng qù shāngdiàn.", "امروز شنبه است، می‌خواهم به فروشگاه بروم.", "Today is Saturday, I want to go to the store.", "Heute ist Samstag, ich will zum Laden gehen."),
   ("我要买一件新衣服。", "Wǒ yào mǎi yí jiàn xīn yīfu.", "می‌خواهم یک لباس نو بخرم.", "I want to buy a new piece of clothing.", "Ich möchte ein neues Kleidungsstück kaufen."),
   ("这件衣服太贵了。", "Zhè jiàn yīfu tài guì le.", "این لباس خیلی گران است.", "This garment is too expensive.", "Dieses Kleid ist zu teuer."),
   ("那件便宜一点儿。", "Nà jiàn piányi yìdiǎnr.", "آن یکی کمی ارزان‌تر است.", "That one is a bit cheaper.", "Das dort ist etwas billiger."),
   ("我买了那件，然后回家。", "Wǒ mǎi le nà jiàn, ránhòu huí jiā.", "آن را خریدم و بعد به خانه رفتم.", "I bought that one, then went home.", "Ich kaufte das und ging dann nach Hause."),
 ]),
 ("r4", 2, ("在饭馆", "در رستوران", "At the restaurant", "Im Restaurant"), [
   ("服务员：你们想吃什么？", "Fúwùyuán: Nǐmen xiǎng chī shénme?", "گارسون: چه میل دارید؟", "Waiter: What would you like to eat?", "Kellner: Was möchten Sie essen?"),
   ("我：我要一碗面条和一杯茶。", "Wǒ: Wǒ yào yì wǎn miàntiáo hé yì bēi chá.", "من: یک کاسه رشته و یک لیوان چای می‌خواهم.", "Me: I'd like a bowl of noodles and a cup of tea.", "Ich: Ich möchte eine Schüssel Nudeln und eine Tasse Tee."),
   ("朋友：我要米饭和鱼。", "Péngyou: Wǒ yào mǐfàn hé yú.", "دوست: من برنج و ماهی می‌خواهم.", "Friend: I want rice and fish.", "Freund: Ich möchte Reis und Fisch."),
   ("饭很好吃！", "Fàn hěn hǎochī!", "غذا خیلی خوشمزه است!", "The food is delicious!", "Das Essen ist lecker!"),
   ("多少钱？一共五十块。", "Duōshao qián? Yígòng wǔshí kuài.", "چقدر می‌شود؟ در مجموع پنجاه یوآن.", "How much? Fifty yuan in total.", "Wie viel kostet es? Insgesamt fünfzig Yuan."),
 ]),
 ("r5", 3, ("我的爱好", "سرگرمی‌های من", "My hobbies", "Meine Hobbys"), [
   ("我有很多爱好，我最喜欢音乐。", "Wǒ yǒu hěn duō àihào, wǒ zuì xǐhuan yīnyuè.", "من سرگرمی‌های زیادی دارم و موسیقی را از همه بیشتر دوست دارم.", "I have many hobbies; I like music most.", "Ich habe viele Hobbys, am liebsten mag ich Musik."),
   ("周末我常常去公园走路。", "Zhōumò wǒ chángcháng qù gōngyuán zǒulù.", "آخر هفته‌ها اغلب برای پیاده‌روی به پارک می‌روم.", "On weekends I often walk in the park.", "Am Wochenende gehe ich oft im Park spazieren."),
   ("虽然工作很忙，但是我每天都锻炼。", "Suīrán gōngzuò hěn máng, dànshì wǒ měitiān dōu duànliàn.", "هرچند کارم شلوغ است، هر روز ورزش می‌کنم.", "Although work is busy, I exercise every day.", "Obwohl die Arbeit stressig ist, trainiere ich jeden Tag."),
   ("我希望以后能去中国旅游。", "Wǒ xīwàng yǐhòu néng qù Zhōngguó lǚyóu.", "امیدوارم بعداً بتوانم برای گردش به چین بروم.", "I hope to travel to China someday.", "Ich hoffe, später nach China reisen zu können."),
 ]),
 ("r6", 3, ("下雨了", "باران آمد", "It's raining", "Es regnet"), [
   ("今天早上天气很好。", "Jīntiān zǎoshang tiānqì hěn hǎo.", "امروز صبح هوا خوب بود.", "The weather was nice this morning.", "Heute Morgen war das Wetter schön."),
   ("下午突然下雨了。", "Xiàwǔ tūrán xià yǔ le.", "بعدازظهر ناگهان باران آمد.", "In the afternoon it suddenly rained.", "Nachmittags begann es plötzlich zu regnen."),
   ("我没有带伞，所以我的衣服都湿了。", "Wǒ méiyǒu dài sǎn, suǒyǐ wǒ de yīfu dōu shī le.", "چتر نیاورده بودم، برای همین لباسم خیس شد.", "I didn't bring an umbrella, so my clothes got wet.", "Ich hatte keinen Schirm dabei, deshalb wurde meine Kleidung nass."),
   ("回家以后，我喝了一杯热茶。", "Huí jiā yǐhòu, wǒ hē le yì bēi rè chá.", "بعد از رسیدن به خانه یک لیوان چای داغ نوشیدم.", "After getting home, I drank a cup of hot tea.", "Zu Hause trank ich eine Tasse heißen Tee."),
 ]),
]

PATH = [  # beginner pinyin path: day -> (kind, arg)
 ("tones", None), ("initials", 0), ("initials", 1), ("finals", 0), ("finals", 1), ("finals", 2), ("rules", None),
]
